# Class attributes

<div class="instructions--content--1JI0g"><div class="udlite-heading-xl instructions--title--3vSDk" data-purpose="exercise-title">Exercise 1</div><div data-purpose="safely-set-inner-html:rich-text-viewer:html" class="udlite-text-sm rt-scaffolding"><p>Implement a class named <em>Phone</em>. In the <em>Phone</em> class, define a class attribute named <em>brand </em>and set its value to <code>'Apple'</code>. Then, using dot notation and <code>print()</code> function, display the value of the <em>brand</em> attribute of the<em> Phone</em> class to the console.</p><p><br></p><p><strong>Expected result:</strong></p><p><br></p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="typ">Apple</span></li></ol></pre></div></div><p><br></p></div></div>

In [2]:
class Phone:
    brand = 'Apple'
 
 
print(Phone.brand)

Apple


<div class="instructions--content--1JI0g"><div class="udlite-heading-xl instructions--title--3vSDk" data-purpose="exercise-title">Exercise 2</div><div data-purpose="safely-set-inner-html:rich-text-viewer:html" class="udlite-text-sm rt-scaffolding"><p>Implement a class named <em>Phone.</em> In the <em>Phone</em> class, define two class attributes with names:</p><ul><li><p><em>brand</em></p></li><li><p><em>model</em></p></li></ul><p>and set their values to:</p><ul><li><p><code>'Apple'</code></p></li><li><p><code>'iPhone X'</code></p></li></ul><p>Then use the built-in functions <code>getattr()</code> and <code>print()</code> to display the values of the given attributes of the <em>Phone</em> class to the console as shown below.</p><p><br></p><p><strong>Expected result:</strong></p><p><br></p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="typ">Apple</span></li><li class="L1"><span class="pln">iPhone&nbsp;X</span></li></ol></pre></div></div><p><br></p></div></div>

In [3]:
class Phone:
    brand = 'Apple'
    model = 'iPhone X'
    
print(Phone.brand)
print(Phone.model)

Apple
iPhone X


<div class="instructions--content--1JI0g"><div class="udlite-heading-xl instructions--title--3vSDk" data-purpose="exercise-title">Exercise 3</div><div data-purpose="safely-set-inner-html:rich-text-viewer:html" class="udlite-text-sm rt-scaffolding"><p>A class named<em> Phone</em> is defined below. Using dot notation, modify the value of the attributes:</p><ul><li><p><em>brand</em> to <code>'Samsung'</code></p></li><li><p><em>model</em> to <code>'Galaxy'</code></p></li></ul><p>In response, print the values for the <em>brand </em>and <em>model </em>attributes to the console as shown below.</p><p><br></p><p><strong>Expected result:</strong></p><p><br></p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="pln">brand</span><span class="pun">:</span><span class="pln">&nbsp;</span><span class="typ">Samsung</span></li><li class="L1"><span class="pln">model</span><span class="pun">:</span><span class="pln">&nbsp;</span><span class="typ">Galaxy</span></li></ol></pre></div></div><p><br></p></div></div>

In [4]:
class Phone:
    brand = 'Apple'
    model = 'iPhone X'
 
 
Phone.brand = 'Samsung'
Phone.model = 'Galaxy'
 
print(f'brand: {Phone.brand}')
print(f'model: {Phone.model}')

brand: Samsung
model: Galaxy


<div class="instructions--content--1JI0g"><div class="udlite-heading-xl instructions--title--3vSDk" data-purpose="exercise-title">Exercise 4</div><div data-purpose="safely-set-inner-html:rich-text-viewer:html" class="udlite-text-sm rt-scaffolding"><p>A class named <em>Laptop</em> is defined below. Using the <code>setattr()</code> built-in function modify the value of attributes:</p><ul><li><p><em>brand</em> to <code>'Acer'</code></p></li><li><p><em>model</em> to <code>'Predator'</code></p></li></ul><p>In response, using the built-in function <code>getattr()</code> and <code>print()</code>, print the values of the <em>brand </em>and <em>model </em>attributes to the console as shown below.</p><p><br></p><p><strong>Expected result:</strong></p><p><br></p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="pln">brand</span><span class="pun">:</span><span class="pln">&nbsp;</span><span class="typ">Acer</span></li><li class="L1"><span class="pln">model</span><span class="pun">:</span><span class="pln">&nbsp;</span><span class="typ">Predator</span></li></ol></pre></div></div><p><br></p></div></div>

In [5]:
class Laptop:
    brand = 'Lenovo'
    model = 'ThinkPad'

setattr(Laptop, 'brand', 'Acer')
setattr(Laptop, 'model', 'Predator')

print(f"brand: {getattr(Laptop, 'brand')}")
print(f"model: {getattr(Laptop, 'model')}")

brand: Acer
model: Predator


<div class="instructions--content--1JI0g"><div class="udlite-heading-xl instructions--title--3vSDk" data-purpose="exercise-title">Exercise 5</div><div data-purpose="safely-set-inner-html:rich-text-viewer:html" class="udlite-text-sm rt-scaffolding"><p>Implement a class named <em>OnlineShop</em> with the class attributes set appropriately:</p><ul><li><p><em>sector</em> to the value <code>'electronics'</code></p></li><li><p><em>sector_code</em> to the value <code>'ELE'</code></p></li><li><p><em>is_public_company </em>to the value <code>False</code></p></li></ul><p>Then, using dot notation, add a class attribute called <em>country</em> and set its value to <code>'USA'</code>. In response, print the user-defined <em>OnlineShop</em> class <strong>attribute names</strong> as shown below.</p><p><br></p><p><strong>Expected result:</strong></p><p><br></p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="pun">[</span><span class="str">'sector'</span><span class="pun">,</span><span class="pln">&nbsp;</span><span class="str">'sector_code'</span><span class="pun">,</span><span class="pln">&nbsp;</span><span class="str">'is_public_company'</span><span class="pun">,</span><span class="pln">&nbsp;</span><span class="str">'country'</span><span class="pun">]</span></li></ol></pre></div></div><p><br></p></div></div>

In [6]:
class OnlineShop:
    sector = 'electronics'
    sector_code = 'ELE'
    is_public_company = False
    
OnlineShop.country = 'USA'

print([attr for attr in OnlineShop.__dict__.keys() if not attr.startswith('_')])

['sector', 'sector_code', 'is_public_company', 'country']


<div class="instructions--content--1JI0g"><div class="udlite-heading-xl instructions--title--3vSDk" data-purpose="exercise-title">Exercise 6</div><div data-purpose="safely-set-inner-html:rich-text-viewer:html" class="udlite-text-sm rt-scaffolding"><p>A class named<em> OnlineShop</em> was defined with the class attributes set accordingly:</p><ul><li><p><em>sector</em> to the value <code>'electronics'</code></p></li><li><p><em>sector_code</em> to the value <code>'ELE'</code></p></li><li><p><em>is_public_company </em>to the value <code>False</code></p></li></ul><p>Using the <code>del</code> statement remove the class attribute named <em>sector_code</em>. In response, print the rest of the user-defined <em>OnlineShop</em> class attribute names as a list as shown below.</p><p><br></p><p><strong>Expected result:</strong></p><p><br></p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="pun">[</span><span class="str">'sector'</span><span class="pun">,</span><span class="pln">&nbsp;</span><span class="str">'is_public_company'</span><span class="pun">]</span></li></ol></pre></div></div><p><br></p></div></div>

In [10]:
class OnlineShop:
    sector = 'electronics'
    sector_code = 'ELE'
    is_public_company = False

del OnlineShop.sector_code
print([attr for attr in OnlineShop.__dict__.keys() if not attr.startswith('_')])

['sector', 'is_public_company']


<div class="instructions--content--1JI0g"><div class="udlite-heading-xl instructions--title--3vSDk" data-purpose="exercise-title">Exercise 7</div><div data-purpose="safely-set-inner-html:rich-text-viewer:html" class="udlite-text-sm rt-scaffolding"><p>A class named <em>OnlineShop </em>was defined with the class attributes set accordingly:</p><ul><li><p><em>sector</em> to the value <code>'electronics'</code></p></li><li><p><em>sector_code</em> to the value <code>'ELE'</code></p></li><li><p><em>is_public_company </em>to the value <code>False</code></p></li></ul><p>Using the builtin <code>delattr()</code> function remove the class attribute <em>sector_code</em>. In response, print the rest of the user-defined <em>OnlineShop</em> class attribute names as a list as shown below.</p><p><br></p><p><strong>Expected result:</strong></p><p><br></p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="pun">[</span><span class="str">'sector'</span><span class="pun">,</span><span class="pln">&nbsp;</span><span class="str">'is_public_company'</span><span class="pun">]</span></li></ol></pre></div></div><p><br></p></div></div>

In [11]:
class OnlineShop:
    sector = 'electronics'
    sector_code = 'ELE'
    is_public_company = False

delattr(OnlineShop, 'sector_code')
print([attr for attr in OnlineShop.__dict__.keys() if not attr.startswith('_')])

['sector', 'is_public_company']


<div class="instructions--content--1JI0g"><div class="udlite-heading-xl instructions--title--3vSDk" data-purpose="exercise-title">Exercise 8</div><div data-purpose="safely-set-inner-html:rich-text-viewer:html" class="udlite-text-sm rt-scaffolding"><p>A class named <em>OnlineShop </em>was defined with the class attributes set accordingly:</p><ul><li><p><em>sector</em> to the value <code>'electronics'</code></p></li><li><p><em>sector_code</em> to the value <code>'ELE'</code></p></li><li><p><em>is_public_company </em>to the value <code>False</code></p></li></ul><p>Display all <strong>user-defined</strong> <em>OnlineShop</em> class attribute names with their values as shown below.</p><p><br></p><p><strong>Expected result:</strong></p><p><br></p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="pln">sector&nbsp;</span><span class="pun">-&gt;</span><span class="pln">&nbsp;electronics</span></li><li class="L1"><span class="pln">sector_code&nbsp;</span><span class="pun">-&gt;</span><span class="pln">&nbsp;ELE</span></li><li class="L2"><span class="pln">is_public_company&nbsp;</span><span class="pun">-&gt;</span><span class="pln">&nbsp;</span><span class="kwd">False</span></li></ol></pre></div></div><p><br></p></div></div>

In [41]:
class OnlineShop:
    sector = 'electronics'
    sector_code = 'ELE'
    is_public_company = False
    
for attr, val in OnlineShop.__dict__.items():
    if not attr.startswith('_'):
        print(f'{attr} -> {val}')

sector -> electronics
sector_code -> ELE
is_public_company -> False


<div class="instructions--content--1JI0g"><div class="udlite-heading-xl instructions--title--3vSDk" data-purpose="exercise-title">Exercise 9</div><div data-purpose="safely-set-inner-html:rich-text-viewer:html" class="udlite-text-sm rt-scaffolding"><p>A class named <em>OnlineShop </em>was defined with the class attributes set accordingly:</p><ul><li><p><em>sector</em> to the value <code>'electronics'</code></p></li><li><p><em>sector_code</em> to the value <code>'ELE'</code></p></li><li><p><em>is_public_company </em>to the value <code>False</code></p></li></ul><p>Outside of the class, implement a function called <code>describe_attrs()</code> that displays the names of all <strong>user-defined class attributes</strong> and their values as shown below. In response, call the <code>describe_attrs()</code> function.</p><p><br></p><p><strong>Expected result:</strong></p><p><br></p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="pln">sector&nbsp;</span><span class="pun">-&gt;</span><span class="pln">&nbsp;electronics</span></li><li class="L1"><span class="pln">sector_code&nbsp;</span><span class="pun">-&gt;</span><span class="pln">&nbsp;ELE</span></li><li class="L2"><span class="pln">is_public_company&nbsp;</span><span class="pun">-&gt;</span><span class="pln">&nbsp;</span><span class="kwd">False</span></li></ol></pre></div></div><p><br></p></div></div>

In [34]:
class OnlineShop:
    sector = 'electronics'
    sector_code = 'ELE'
    is_public_company = False
    
def describe_attrs():
    for attr, val in OnlineShop.__dict__.items():
        if not attr.startswith('_'):
            print(f'{attr} -> {val}')
            
describe_attrs()

<div class="instructions--content--1JI0g"><div class="udlite-heading-xl instructions--title--3vSDk" data-purpose="exercise-title">Exercise 10</div><div data-purpose="safely-set-inner-html:rich-text-viewer:html" class="udlite-text-sm rt-scaffolding"><p>A class named <em>OnlineShop </em>was defined with the class attributes set accordingly:</p><ul><li><p><em>sector</em> to the value <code>'electronics'</code></p></li><li><p><em>sector_code</em> to the value <code>'ELE'</code></p></li><li><p><em>is_public_company </em>to the value <code>False</code></p></li></ul><p>Implement a function (class callable attribute) named <code>get_sector()</code> that returns the value of the <em>sector </em>attribute of <em>OnlineShop </em>class. You only need to implement this function.</p><p><br></p></div></div>

In [57]:
class OnlineShop:
    sector = 'electronics'
    sector_code = 'ELE'
    is_public_company = False
    
    def get_sector():
        return(OnlineShop.__dict__['sector'])

<div class="instructions--content--1JI0g"><div class="udlite-heading-xl instructions--title--3vSDk" data-purpose="exercise-title">Exercise 11</div><div data-purpose="safely-set-inner-html:rich-text-viewer:html" class="udlite-text-sm rt-scaffolding"><p>Implement the <em>HouseProject </em>class with class attributes respectively:</p><ul><li><p><code>number_of_floors = 3</code></p></li><li><p><code>area = 100</code></p></li></ul><p>Then, in the <em>HouseProject </em>class implement a function (class callable attribute) called <code>describe_project()</code>, which displays basic information about the project as follows:</p><p><br></p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="typ">Floor</span><span class="pln">&nbsp;number</span><span class="pun">:</span><span class="pln">&nbsp;</span><span class="lit">3</span></li><li class="L1"><span class="typ">Area</span><span class="pun">:</span><span class="pln">&nbsp;</span><span class="lit">100</span></li></ol></pre></div></div><p>In response, call <code>describe_project()</code> function.</p><p><br></p><p><strong>Expected result:</strong></p><p><br></p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="typ">Floor</span><span class="pln">&nbsp;number</span><span class="pun">:</span><span class="pln">&nbsp;</span><span class="lit">3</span></li><li class="L1"><span class="typ">Area</span><span class="pun">:</span><span class="pln">&nbsp;</span><span class="lit">100</span></li></ol></pre></div></div><p><br></p></div></div>

In [67]:
class HouseProject:
    number_of_floors = 3
    area = 100
    
    def describe_project():
        print(f'Floor number: {HouseProject.number_of_floors}')
        print(f'Area: {HouseProject.area}')

HouseProject.describe_project()        

Floor number: 3
Area: 100


# Instance attributes

<div class="instructions--content--1JI0g"><div class="udlite-heading-xl instructions--title--3vSDk" data-purpose="exercise-title">Exercise 1</div><div data-purpose="safely-set-inner-html:rich-text-viewer:html" class="udlite-text-sm rt-scaffolding"><p>The <em>Book </em>class is defined. Create an instance of the <em>Book</em> class named <em>book</em>. Display the value of the <code>__dict__</code> attribute for the <em>book</em> instance. Then assign two attributes to the <em>book</em> instance:</p><ul><li><p><em>author </em>to the value <code>'Dan Brown'</code></p></li><li><p><em>title</em> to the value <code>'Inferno'</code></p></li></ul><p>In response, display the <code>__dict__</code> attribute for the <em>book</em> instance again.</p><p><br></p><p><strong>Expected result:</strong></p><p><br></p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="pun">{}</span></li><li class="L1"><span class="pun">{</span><span class="str">'author'</span><span class="pun">:</span><span class="pln">&nbsp;</span><span class="str">'Dan&nbsp;Brown'</span><span class="pun">,</span><span class="pln">&nbsp;</span><span class="str">'title'</span><span class="pun">:</span><span class="pln">&nbsp;</span><span class="str">'Inferno'</span><span class="pun">}</span></li></ol></pre></div></div><p><br></p></div></div>

In [69]:
class Book:
    language = 'ENG'
    is_ebook = True

In [75]:
book = Book()
print(book.__dict__)
book.__dict__ = {'author': 'Dan Brown', 'title': 'Inferno'}
print(book.__dict__)

{}
{'author': 'Dan Brown', 'title': 'Inferno'}


<div class="instructions--content--1JI0g"><div class="udlite-heading-xl instructions--title--3vSDk" data-purpose="exercise-title">Exercise 2</div><div data-purpose="safely-set-inner-html:rich-text-viewer:html" class="udlite-text-sm rt-scaffolding"><p>The <em>Book</em> class is defined. Create two instances of the <em>Book</em> class named <em>book_1</em> and <em>book_2</em>. Then assign instance attributes to these objects (using dot notation) as follows:</p><ul><li><p>to object <em>book_1</em>:</p><ul><li><p><code>author = 'Dan Brown'</code></p></li><li><p><code>title = 'Inferno'</code></p></li></ul></li><li><p>to object <em>book_2</em>:</p><ul><li><p><code>author = 'Dan Brown'</code></p></li><li><p><code>title = 'The Da Vinci Code'</code></p></li><li><p><code>year_of_publishment = 2003</code></p></li></ul></li></ul><p>In response, print the value of the <code>__dict__</code> attribute of <em>book_1 </em>and <em>book_2</em>.</p><p><br></p><p><strong>Expected result:</strong></p><p><br></p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="pun">{</span><span class="str">'author'</span><span class="pun">:</span><span class="pln">&nbsp;</span><span class="str">'Dan&nbsp;Brown'</span><span class="pun">,</span><span class="pln">&nbsp;</span><span class="str">'title'</span><span class="pun">:</span><span class="pln">&nbsp;</span><span class="str">'Inferno'</span><span class="pun">}</span></li><li class="L1"><span class="pun">{</span><span class="str">'author'</span><span class="pun">:</span><span class="pln">&nbsp;</span><span class="str">'Dan&nbsp;Brown'</span><span class="pun">,</span><span class="pln">&nbsp;</span><span class="str">'title'</span><span class="pun">:</span><span class="pln">&nbsp;</span><span class="str">'The&nbsp;Da&nbsp;Vinci&nbsp;Code'</span><span class="pun">,</span><span class="pln">&nbsp;</span><span class="str">'year_of_publishment'</span><span class="pun">:</span><span class="pln">&nbsp;</span><span class="lit">2003</span><span class="pun">}</span></li></ol></pre></div></div><p><br></p></div></div>

In [78]:
class Book:
    language = 'ENG'
    is_ebook = True

In [77]:
book_1 = Book()
book_2 = Book()
book_1.__dict__ = {'author': 'Dan Brown', 'title': 'Inferno'}
print(book_1.__dict__)
book_2.author = 'Dan Brown'
book_2.title = 'The Da Vinci Code'
book_2.year_of_publishment = 2003
print(book_2.__dict__)

{'author': 'Dan Brown', 'title': 'Inferno'}
{'author': 'Dan Brown', 'title': 'The Da Vinci Code', 'year_of_publishment': 2003}


<div class="instructions--content--1JI0g"><div class="udlite-heading-xl instructions--title--3vSDk" data-purpose="exercise-title">Exercise 3</div><div data-purpose="safely-set-inner-html:rich-text-viewer:html" class="udlite-text-sm rt-scaffolding"><p>The <em>Book </em>class is defined. Two instances of the <em>Book </em>class named <em>book_1 </em>and <em>book_2 </em>was created. Then the instance attributes were assigned to these objects (using the dot notation), respectively:</p><ul><li><p>to object <em>book_1</em>:</p><ul><li><p><code>author = 'Dan Brown'</code></p></li><li><p><code>title = 'Inferno'</code></p></li></ul></li><li><p>to object <em>book_2</em>:</p><ul><li><p><code>author = 'Dan Brown'</code></p></li><li><p><code>title = 'The Da Vinci Code'</code></p></li><li><p><code>year_of_publishment = 2003</code></p></li></ul></li></ul><p>Then a <em>books </em>list was created. Create a loop to list all the attributes of the <em>book_1 </em>and <em>book_2 </em>instances with their values as shown below (separate each instance with a line of 30 <code>'-'</code> characters&nbsp; as shown below).</p><p><br></p><p><strong>Expected result:</strong></p><p><br></p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="pln">author </span><span class="pun">-&gt;</span><span class="pln"> </span><span class="typ">Dan</span><span class="pln"> </span><span class="typ">Brown</span></li><li class="L1"><span class="pln">title </span><span class="pun">-&gt;</span><span class="pln"> </span><span class="typ">Inferno</span></li><li class="L2"><span class="pun">------------------------------</span></li><li class="L3"><span class="pln">author </span><span class="pun">-&gt;</span><span class="pln"> </span><span class="typ">Dan</span><span class="pln"> </span><span class="typ">Brown</span></li><li class="L4"><span class="pln">title </span><span class="pun">-&gt;</span><span class="pln"> </span><span class="typ">The</span><span class="pln"> </span><span class="typ">Da</span><span class="pln"> </span><span class="typ">Vinci</span><span class="pln"> </span><span class="typ">Code</span></li><li class="L5"><span class="pln">year_of_publishment </span><span class="pun">-&gt;</span><span class="pln"> </span><span class="lit">2003</span></li><li class="L6"><span class="pun">------------------------------</span></li></ol></pre></div></div><p><br></p></div></div>

In [79]:
class Book:
    language = 'ENG'
    is_ebook = True


book_1 = Book()
book_2 = Book()

book_1.author = 'Dan Brown'
book_1.title = 'Inferno'

book_2.author = 'Dan Brown'
book_2.title = 'The Da Vinci Code'
book_2.year_of_publishment = 2003

books = [book_1, book_2]

In [87]:
for book in books:
    for key, val in book.__dict__.items():
        print(f'{key} -> {val}')
    print('------------------------------')

author -> Dan Brown
title -> Inferno
------------------------------
author -> Dan Brown
title -> The Da Vinci Code
year_of_publishment -> 2003
------------------------------


<div class="instructions--content--1JI0g"><div class="udlite-heading-xl instructions--title--3vSDk" data-purpose="exercise-title">Exercise 4</div><div data-purpose="safely-set-inner-html:rich-text-viewer:html" class="udlite-text-sm rt-scaffolding"><p>The <em>Book </em>class is defined. A list <em>books_data</em> is also given. </p><p><br></p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="pln">books_data </span><span class="pun">=</span><span class="pln"> </span><span class="pun">[</span></li><li class="L1"><span class="pln">    </span><span class="pun">{</span><span class="str">'author'</span><span class="pun">:</span><span class="pln"> </span><span class="str">'Dan Brown'</span><span class="pun">,</span><span class="pln"> </span><span class="str">'title'</span><span class="pun">:</span><span class="pln"> </span><span class="str">'Inferno'</span><span class="pun">},</span></li><li class="L2"><span class="pln">    </span><span class="pun">{</span><span class="str">'author'</span><span class="pun">:</span><span class="pln"> </span><span class="str">'Dan Brown'</span><span class="pun">,</span><span class="pln"> </span><span class="str">'title'</span><span class="pun">:</span><span class="pln"> </span><span class="str">'The Da Vinci Code'</span><span class="pun">,</span><span class="pln"> </span><span class="str">'year_of_publishment'</span><span class="pun">:</span><span class="pln"> </span><span class="lit">2003</span><span class="pun">}</span></li><li class="L3"><span class="pun">]</span></li></ol></pre></div></div><p>Based on this data, create two instances of the <em>Book </em>class, where the instance attributes will be the keys from the given dictionaries (<em>books_data </em>list) with their corresponding values. </p><p>In response, print the <code>__dict__</code> attributes of the objects to the console as shown below.</p><p><br></p><p><strong>Expected result:</strong></p><p><br></p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="pun">{</span><span class="str">'author'</span><span class="pun">:</span><span class="pln">&nbsp;</span><span class="str">'Dan&nbsp;Brown'</span><span class="pun">,</span><span class="pln">&nbsp;</span><span class="str">'title'</span><span class="pun">:</span><span class="pln">&nbsp;</span><span class="str">'Inferno'</span><span class="pun">}</span></li><li class="L1"><span class="pun">{</span><span class="str">'author'</span><span class="pun">:</span><span class="pln">&nbsp;</span><span class="str">'Dan&nbsp;Brown'</span><span class="pun">,</span><span class="pln">&nbsp;</span><span class="str">'title'</span><span class="pun">:</span><span class="pln">&nbsp;</span><span class="str">'The&nbsp;Da&nbsp;Vinci&nbsp;Code'</span><span class="pun">,</span><span class="pln">&nbsp;</span><span class="str">'year_of_publishment'</span><span class="pun">:</span><span class="pln">&nbsp;</span><span class="lit">2003</span><span class="pun">}</span></li></ol></pre></div></div><p><br></p></div></div>

In [88]:
class Book:
    language = 'ENG'
    is_ebook = True


books_data = [
    {'author': 'Dan Brown', 'title': 'Inferno'},
    {'author': 'Dan Brown', 'title': 'The Da Vinci Code', 'year_of_publishment': 2003}
]

In [90]:
book_1 = Book()
book_2 = Book()

book_1.__dict__ = books_data[0]
book_2.__dict__ = books_data[1]

print(book_1.__dict__)
print(book_2.__dict__)

{'author': 'Dan Brown', 'title': 'Inferno'}
{'author': 'Dan Brown', 'title': 'The Da Vinci Code', 'year_of_publishment': 2003}


In [91]:
books = []
for book_data in books_data:
    book = Book()
    for attr, value in book_data.items():
        setattr(book, attr, value)
    books.append(book)
 
for book in books:
    print(book.__dict__)

{'author': 'Dan Brown', 'title': 'Inferno'}
{'author': 'Dan Brown', 'title': 'The Da Vinci Code', 'year_of_publishment': 2003}


<div class="instructions--content--1JI0g"><div class="udlite-heading-xl instructions--title--3vSDk" data-purpose="exercise-title">Exercise 5</div><div data-purpose="safely-set-inner-html:rich-text-viewer:html" class="udlite-text-sm rt-scaffolding"><p>The <em>Book </em>class is defined. Implement a method called <code>set_title()</code> that allows you to set an instance attribute called <em>title</em> (without validation). Then create an instance of the <em>Book </em>class named <em>book </em>and set the <em>title </em>attribute to <code>'Inferno'</code> using the <code>set_title()</code> method.</p><p>In response, print the value of the <em>title </em>attribute of the <em>book </em>instance.</p><p><br></p><p><strong>Expected result:</strong></p><p><br></p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="typ">Inferno</span></li></ol></pre></div></div><p><br></p></div></div>

In [92]:
class Book:
    language = 'ENG'
    is_ebook = True

In [113]:
class Book:
    language = 'ENG'
    is_ebook = True
    
    def set_title(self, value):
        self.title = value       

In [116]:
book = Book()
book.set_title("Inferno")
print(book.title)

Inferno


<div class="instructions--content--1JI0g"><div class="udlite-heading-xl instructions--title--3vSDk" data-purpose="exercise-title">Exercise 6</div><div data-purpose="safely-set-inner-html:rich-text-viewer:html" class="udlite-text-sm rt-scaffolding"><p>The <em>Book </em>class is defined. Implement a method named <code>set_title()</code> that sets an instance attribute named <em>title</em>. Before setting the value, check if it's an object of <code>str</code> type, if not raise a <code>TypeError</code> with the following message:</p><p><br></p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="str">'The&nbsp;value&nbsp;of&nbsp;the&nbsp;title&nbsp;attribute&nbsp;must&nbsp;be&nbsp;of&nbsp;str&nbsp;type.'</span></li></ol></pre></div></div><p>Then create an instance of the <em>Book </em>class named <em>book </em>and set the <em>title </em>attribute to <code>'Inferno'</code> using the <code>set_title()</code> method.</p><p>In response, print the value of the <em>title </em>attribute of the <em>book </em>instance.</p><p><br></p><p><strong>Expected result:</strong></p><p><br></p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="typ">Inferno</span></li></ol></pre></div></div><p><br></p></div></div>

In [117]:
class Book:
    language = 'ENG'
    is_ebook = True

In [138]:
class Book:
    language = 'ENG'
    is_ebook = True
    
    def set_title(self, value):
        if type(value) == str:
            self.title = value
        else:
            raise TypeError('The value of the title attribute must be of str type.')

book = Book()
book.set_title("Inferno")
print(book.title)

<div class="instructions--content--1JI0g"><div class="udlite-heading-xl instructions--title--3vSDk" data-purpose="exercise-title">Exercise 7</div><div data-purpose="safely-set-inner-html:rich-text-viewer:html" class="udlite-text-sm rt-scaffolding"><p>The <em>Book </em>class is defined. A method called <code>set_title()</code> was implemented that allows you to set an instance attribute called <em>title</em>. Create an instance of the <em>Book </em>class named <em>book</em>. Then, using the <code>try ... except ...</code> clause, try using the <code>set_title()</code> method to set the value of the <em>title </em>attribute to <code>False</code>. In case of a <code>TypeError</code>, print the error message to the console.</p><p><br></p><p><strong>Expected result:</strong></p><p><br></p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="typ">The</span><span class="pln"> value of the title attribute must be of str type</span><span class="pun">.</span></li></ol></pre></div></div><p><br></p></div></div>

In [145]:
class Book:
    language = 'ENG'
    is_ebook = True

    def set_title(self, value):
        if not isinstance(value, str):
            raise TypeError('The value of the title attribute must be of str '
                'type.')
        self.title = value

In [146]:
book = Book()
 
try:
    book.set_title(False)
except TypeError as error:
    print(error)

The value of the title attribute must be of str type.


# The \_\_init\_\_ method()

<div class="instructions--content--1JI0g"><div class="udlite-heading-xl instructions--title--3vSDk" data-purpose="exercise-title">Exercise 1</div><div data-purpose="safely-set-inner-html:rich-text-viewer:html" class="udlite-text-sm rt-scaffolding"><p>Implement a class called <em>Laptop </em>that sets the following instance attributes when creating an instance:</p><ul><li><p><em>brand</em></p></li><li><p><em>model</em></p></li><li><p><em>price</em></p></li></ul><p>Then create an instance named <em>laptop </em>with the following attribute values:</p><ul><li><p><code>brand = 'Acer'</code></p></li><li><p><code>model = 'Predator'</code></p></li><li><p><code>price = 5490</code></p></li></ul><p><br></p><p><strong>Tip: </strong>Use the special method <code>__init__()</code>.</p><p><br></p><p>In response, print the value of the <code>__dict__</code> attribute of the <em>laptop </em>instance.</p><p><br></p><p><strong>Expected result:</strong></p><p><br></p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="pun">{</span><span class="str">'brand'</span><span class="pun">:</span><span class="pln">&nbsp;</span><span class="str">'Acer'</span><span class="pun">,</span><span class="pln">&nbsp;</span><span class="str">'model'</span><span class="pun">:</span><span class="pln">&nbsp;</span><span class="str">'Predator'</span><span class="pun">,</span><span class="pln">&nbsp;</span><span class="str">'price'</span><span class="pun">:</span><span class="pln">&nbsp;</span><span class="lit">5490</span><span class="pun">}</span></li></ol></pre></div></div><p><br></p></div></div>

In [155]:
class Laptop:
    def __init__(self, brand, model, price):
        self.brand = brand
        self.model = model
        self.price = price
        
laptop = Laptop('Acer', 'Predator', 5490)
print(laptop.__dict__)

{'brand': 'Acer', 'model': 'Predator', 'price': 5490}


<div class="instructions--content--1JI0g"><div class="udlite-heading-xl instructions--title--3vSDk" data-purpose="exercise-title">Exercise 2</div><div data-purpose="safely-set-inner-html:rich-text-viewer:html" class="udlite-text-sm rt-scaffolding"><p>A class called <em>Laptop </em>was implemented.</p><p>Implement a method in the <em>Laptop </em>class called <code>display_instance_attrs()</code> that displays <strong>the names</strong> of all the attributes of the <em>Laptop </em>instance.</p><p>Then create an instance named <em>laptop </em>with the given attribute values:</p><ul><li><p><code>brand = 'Dell'</code></p></li><li><p><code>model = 'Inspiron'</code></p></li><li><p><code>price = 3699</code></p></li></ul><p>In response, call <code>display_instance_attrs()</code> method on the <em>laptop </em>instance.</p><p><br></p><p><strong>Expected result:</strong></p><p><br></p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="pln">brand</span></li><li class="L1"><span class="pln">model</span></li><li class="L2"><span class="pln">price</span></li></ol></pre></div></div><p><br></p></div></div>

In [241]:
class Laptop:
    
    def __init__(self, brand, model, price):
        self.brand = brand
        self.model = model
        self.price = price
    
    def display_instance_attrs(self):
        for attr in self.__dict__.keys():
            if not attr.startswith('_'):
                print(attr)

In [242]:
laptop = Laptop('Dell', 'Inspiron', 3699)
laptop.display_instance_attrs()

brand
model
price


<div class="instructions--content--1JI0g"><div class="udlite-heading-xl instructions--title--3vSDk" data-purpose="exercise-title">Exercise 3</div><div data-purpose="safely-set-inner-html:rich-text-viewer:html" class="udlite-text-sm rt-scaffolding"><p>A class called <em>Laptop </em>was implemented.</p><p>Implement a method in the <em>Laptop </em>class called <code>display_attrs_with_values()</code>, which displays the names of all the attributes of the <em>Laptop</em> class with their values as shown below (attribute name -&gt; attribute value).</p><p>Then create an instance named <em>laptop </em>with the following values:</p><ul><li><p><code>brand = 'Dell'</code></p></li><li><p><code>model = 'Inspiron'</code></p></li><li><p><code>price = 3699</code></p></li></ul><p>In response, call <code>display_attrs_with_values()</code> method on the <em>laptop </em>instance.</p><p><br></p><p><strong>Expected result:</strong></p><p><br></p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="pln">brand </span><span class="pun">-&gt;</span><span class="pln"> </span><span class="typ">Dell</span></li><li class="L1"><span class="pln">model </span><span class="pun">-&gt;</span><span class="pln"> </span><span class="typ">Inspiron</span></li><li class="L2"><span class="pln">price </span><span class="pun">-&gt;</span><span class="pln"> </span><span class="lit">3699</span></li></ol></pre></div></div><p><br></p></div></div>

In [172]:
class Laptop:

    def __init__(self, brand, model, price):
        self.brand = brand
        self.model = model
        self.price = price
    
    def display_attrs_with_values(self):
        for attr, val in self.__dict__.items():
            if not attr.startswith('_'):
                print(f'{attr} -> {val}')

In [174]:
laptop = Laptop('Dell', 'Inspiron', 3699)
laptop.display_attrs_with_values()

brand -> Dell
model -> Inspiron
price -> 3699


<div class="instructions--content--1JI0g"><div class="udlite-heading-xl instructions--title--3vSDk" data-purpose="exercise-title">Exercise 4</div><div data-purpose="safely-set-inner-html:rich-text-viewer:html" class="udlite-text-sm rt-scaffolding"><p>Implement a class named <em>Vector </em>that takes any number of n-dimensional vector coordinates as arguments when creating an instance (without any validation) and assign to instance attribute named <em>components</em>. Then create two instances with following coordinates:</p><ul><li><p><code>(1, 2)</code></p></li><li><p><code>(4, 5, 2)</code></p></li></ul><p>and assign to variables <em>v1 </em>and <em>v2 </em>respectively. </p><p>In response, print the value of the <em>components </em>attribute for <em>v1 </em>and v2 instance as shown below.</p><p><br></p><p><strong>Expected result:</strong></p><p><br></p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="pln">v1&nbsp;</span><span class="pun">-&gt;</span><span class="pln">&nbsp;</span><span class="pun">(</span><span class="lit">1</span><span class="pun">,</span><span class="pln">&nbsp;</span><span class="lit">2</span><span class="pun">)</span></li><li class="L1"><span class="pln">v2&nbsp;</span><span class="pun">-&gt;</span><span class="pln">&nbsp;</span><span class="pun">(</span><span class="lit">4</span><span class="pun">,</span><span class="pln">&nbsp;</span><span class="lit">5</span><span class="pun">,</span><span class="pln">&nbsp;</span><span class="lit">2</span><span class="pun">)</span></li></ol></pre></div></div><p><br></p></div></div>

In [176]:
class Vector:
    def __init__(self, *components):
        self.components = components
        

In [182]:
v1 = Vector(1, 2)
v2 = Vector(4, 5, 2)

print(f'v1 -> {v1.components}')
print(f'v2 -> {v2.components}')

<div class="instructions--content--1JI0g"><div class="udlite-heading-xl instructions--title--3vSDk" data-purpose="exercise-title">Exercise 5</div><div data-purpose="safely-set-inner-html:rich-text-viewer:html" class="udlite-text-sm rt-scaffolding"><p>Implement a class called <em>Bucket </em>that takes any number of named arguments (keyword arguments - use <code>**kwargs</code>) when creating an instance. The name of the argument is the name of the instance attribute, and the value for the argument is the value for the instance attribute.</p><p><br></p><p><strong>Example:</strong></p><p><br></p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="pun">[</span><span class="pln">IN</span><span class="pun">]:</span><span class="pln"> bucket&nbsp;</span><span class="pun">=</span><span class="pln">&nbsp;</span><span class="typ">Bucket</span><span class="pun">(</span><span class="pln">apple</span><span class="pun">=</span><span class="lit">3.5</span><span class="pun">)</span></li><li class="L1"><span class="pun">[</span><span class="pln">IN</span><span class="pun">]:</span><span class="pln"> </span><span class="kwd">print</span><span class="pun">(</span><span class="pln">bucket</span><span class="pun">.</span><span class="pln">__dict__</span><span class="pun">)</span></li></ol></pre></div></div><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="pun">[</span><span class="pln">OUT</span><span class="pun">]:</span><span class="pln"> </span><span class="pun">{</span><span class="str">'apple'</span><span class="pun">:</span><span class="pln">&nbsp;</span><span class="lit">3.5</span><span class="pun">}</span></li></ol></pre></div></div><p>Then create<em> </em>instance named <em>bucket </em>by adding the following attributes with their values:</p><ul><li><p><code>apple = 3.5</code></p></li><li><p><code>milk = 2.5</code></p></li><li><p><code>juice = 4.9</code></p></li><li><p><code>water = 2.5</code></p></li></ul><p>In response, print the value of <code>__dict__</code> attribute for the <em>bucket </em>instance.</p><p><br></p><p><strong>Expected result:</strong></p><p><br></p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="pun">{</span><span class="str">'apple'</span><span class="pun">:</span><span class="pln">&nbsp;</span><span class="lit">3.5</span><span class="pun">,</span><span class="pln">&nbsp;</span><span class="str">'milk'</span><span class="pun">:</span><span class="pln">&nbsp;</span><span class="lit">2.5</span><span class="pun">,</span><span class="pln">&nbsp;</span><span class="str">'juice'</span><span class="pun">:</span><span class="pln">&nbsp;</span><span class="lit">4.9</span><span class="pun">,</span><span class="pln">&nbsp;</span><span class="str">'water'</span><span class="pun">:</span><span class="pln">&nbsp;</span><span class="lit">2.5</span><span class="pun">}</span></li></ol></pre></div></div><p><br></p></div></div>

In [222]:
class Bucket():
    def __init__(self, **kwargs):
        for key, item in kwargs.items():
            setattr(self, key, item)      

In [223]:
bucket = Bucket(apple=3.5, milk=2.5, juice=4.9, water=2.5)
print(bucket.__dict__)

{'apple': 3.5, 'milk': 2.5, 'juice': 4.9, 'water': 2.5}


<div class="instructions--content--1JI0g"><div class="udlite-heading-xl instructions--title--3vSDk" data-purpose="exercise-title">Exercise 6</div><div data-purpose="safely-set-inner-html:rich-text-viewer:html" class="udlite-text-sm rt-scaffolding"><p>Implement a class called <em>Car </em>that sets the following instance attributes when creating an instance:</p><ul><li><p><em>brand</em></p></li><li><p><em>model</em></p></li><li><p><em>price</em></p></li><li><p><em>type_of_car</em>, by default <code>'sedan'</code></p></li></ul><p>Then create an instance<em> </em>named <em>car </em>with the given values:</p><ul><li><p><code>brand = 'Opel'</code></p></li><li><p><code>model = 'Insignia'</code></p></li><li><p><code>price = 115000</code></p></li></ul><p>In response, print the value of the <code>__dict__</code> attribute of the <em>car </em>instance.</p><p><br></p><p><strong>Expected result:</strong></p><p><br></p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="pun">{</span><span class="str">'brand'</span><span class="pun">:</span><span class="pln">&nbsp;</span><span class="str">'Opel'</span><span class="pun">,</span><span class="pln">&nbsp;</span><span class="str">'model'</span><span class="pun">:</span><span class="pln">&nbsp;</span><span class="str">'Insignia'</span><span class="pun">,</span><span class="pln">&nbsp;</span><span class="str">'price'</span><span class="pun">:</span><span class="pln">&nbsp;</span><span class="lit">115000</span><span class="pun">,</span><span class="pln">&nbsp;</span><span class="str">'type_of_car'</span><span class="pun">:</span><span class="pln">&nbsp;</span><span class="str">'sedan'</span><span class="pun">}</span></li></ol></pre></div></div><p><br></p></div></div>

In [228]:
class Car:
    
    def __init__(self, brand, model, price, type_of_car = 'sedan'):
        self.brand = brand
        self.model = model
        self.price = price
        self.type_of_car = type_of_car

In [229]:
car = Car('Opel', 'Insignia', 115000)
print(car.__dict__)

{'brand': 'Opel', 'model': 'Insignia', 'price': 115000, 'type_of_car': 'sedan'}


<div class="instructions--content--1JI0g"><div class="udlite-heading-xl instructions--title--3vSDk" data-purpose="exercise-title">Exercise 7</div><div data-purpose="safely-set-inner-html:rich-text-viewer:html" class="udlite-text-sm rt-scaffolding"><p>A class called <em>Car </em>was implemented that sets the following instance attributes when creating an instance:</p><ul><li><p><em>brand</em></p></li><li><p><em>model</em></p></li><li><p><em>price</em></p></li><li><p><em>type_of_car</em>, by default <code>'sedan'</code></p></li></ul><p>Then create an instance of this<em> </em>named <em>car </em>with the given values:</p><ul><li><p><code>brand = 'BMW'</code></p></li><li><p><code>model = 'X3'</code></p></li><li><p><code>price = 200000</code></p></li><li><p><code>type_of_car = 'SUV'</code></p></li></ul><p>In response, print the value of the <code>__dict__</code> attribute of the <em>car </em>instance.</p><p><br></p><p><strong>Expected result:</strong></p><p><br></p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="pun">{</span><span class="str">'brand'</span><span class="pun">:</span><span class="pln"> </span><span class="str">'BMW'</span><span class="pun">,</span><span class="pln"> </span><span class="str">'model'</span><span class="pun">:</span><span class="pln"> </span><span class="str">'X3'</span><span class="pun">,</span><span class="pln"> </span><span class="str">'price'</span><span class="pun">:</span><span class="pln"> </span><span class="lit">200000</span><span class="pun">,</span><span class="pln"> </span><span class="str">'type_of_car'</span><span class="pun">:</span><span class="pln"> </span><span class="str">'SUV'</span><span class="pun">}</span></li></ol></pre></div></div><p><br></p></div></div>

In [231]:
class Car:

    def __init__(self, brand, model, price, type_of_car=None):
        self.brand = brand
        self.model = model
        self.price = price
        self.type_of_car = type_of_car if type_of_car else 'sedan'

In [232]:
car = Car('BMW', 'X3', 200000, 'SUV')
print(car.__dict__)

{'brand': 'BMW', 'model': 'X3', 'price': 200000, 'type_of_car': 'SUV'}


<div class="instructions--content--1JI0g"><div class="udlite-heading-xl instructions--title--3vSDk" data-purpose="exercise-title">Exercise 8</div><div data-purpose="safely-set-inner-html:rich-text-viewer:html" class="udlite-text-sm rt-scaffolding"><p>Implement a class called <em>Laptop </em>that sets the following instance attributes when creating an instance:</p><ul><li><p><em>brand</em></p></li><li><p><em>model</em></p></li><li><p><em>price</em></p></li></ul><p>When creating an instance, add validation for the <em>price </em>attribute. The value of the <em>price </em>attribute must be an <code>int</code> or <code>float</code> type greater than zero. If it is not, raise the <code>TypeError </code>with the following message:</p><p><br></p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="str">'The&nbsp;price&nbsp;attribute&nbsp;must&nbsp;be&nbsp;a&nbsp;positive&nbsp;int&nbsp;or&nbsp;float.'</span></li></ol></pre></div></div><p>Then create an instance called <em>laptop </em>with the given attributes:</p><ul><li><p><code>brand = 'Acer'</code></p></li><li><p><code>model = 'Predator'</code></p></li><li><p><code>price = 5490</code></p></li></ul><p>In response, print the value of the <code>__dict__</code> attribute of the <em>laptop </em>instance.</p><p><br></p><p><strong>Expected result:</strong></p><p><br></p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="pun">{</span><span class="str">'brand'</span><span class="pun">:</span><span class="pln">&nbsp;</span><span class="str">'Acer'</span><span class="pun">,</span><span class="pln">&nbsp;</span><span class="str">'model'</span><span class="pun">:</span><span class="pln">&nbsp;</span><span class="str">'Predator'</span><span class="pun">,</span><span class="pln">&nbsp;</span><span class="str">'price'</span><span class="pun">:</span><span class="pln">&nbsp;</span><span class="lit">5490</span><span class="pun">}</span></li></ol></pre></div></div><p><br></p></div></div>

In [72]:
class Laptop:

    def __init__(self, brand, model, price):
        self.brand = brand
        self.model = model
        if isinstance(price, (int, float))  and price >= 0:
            self.price = price
        else:
            raise TypeError('The price attribute must be a positive int or float.')

In [75]:
laptop = Laptop('Acer', 'Predator', 5490)
print(laptop.__dict__)

{'brand': 'Acer', 'model': 'Predator', 'price': 5490}


<div class="instructions--content--1JI0g"><div class="udlite-heading-xl instructions--title--3vSDk" data-purpose="exercise-title">Exercise 9</div><div data-purpose="safely-set-inner-html:rich-text-viewer:html" class="udlite-text-sm rt-scaffolding"><p>A class called <em>Laptop </em>was implemented.</p><p>Try to create an instance named <em>laptop </em>with the given attribute values:</p><ul><li><p><code>brand = 'Acer'</code></p></li><li><p><code>model = 'Predator'</code></p></li><li><p><code>price = '5900'</code></p></li></ul><p>Note that in this case the value of the <em>price </em>attribute is passed as a <code>str</code> type. In case of error, print the error message to the console (use the <code>try ... except ...</code> clause).</p><p><br></p><p><strong>Expected result:</strong></p><p><br></p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="typ">The</span><span class="pln"> price attribute must be a positive </span><span class="kwd">int</span><span class="pln"> </span><span class="kwd">or</span><span class="pln"> </span><span class="kwd">float</span><span class="pun">.</span></li></ol></pre></div></div><p><br></p></div></div>

In [ ]:
class Laptop:

    def __init__(self, brand, model, price):
        self.brand = brand
        self.model = model
        if isinstance(price, (int, float)) and price > 0:
            self.price = price
        else:
            raise TypeError('The price attribute must be a positive int or float.')

In [239]:
try:
    laptop = Laptop('Acer', 'Predator', '5900')
except TypeError as error:
    print(error)

The price attribute must be a positive int or float.


# Visibility of variables

<div class="instructions--content--1JI0g"><div class="udlite-heading-xl instructions--title--3vSDk" data-purpose="exercise-title">Exercise 1</div><div data-purpose="safely-set-inner-html:rich-text-viewer:html" class="udlite-text-sm rt-scaffolding"><p>Implement a class called <em>Laptop </em>that sets the following instance attributes when creating an instance:</p><ul><li><p><em>brand </em>as a bare instance attribute</p></li><li><p><em>model </em>as a protected attribute</p></li><li><p><em>price</em> as a private attribute</p></li></ul><p>Then create an instance named <em>laptop </em>with the following arguments:</p><ul><li><p><code>'Acer'</code></p></li><li><p><code>'Predator'</code></p></li><li><p><code>5490</code></p></li></ul><p>In response, print the value of the <code>__dict__</code> attribute of the <em>laptop </em>instance.</p><p><br></p><p><strong>Expected result:</strong></p><p><br></p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="pun">{</span><span class="str">'brand'</span><span class="pun">:</span><span class="pln">&nbsp;</span><span class="str">'Acer'</span><span class="pun">,</span><span class="pln">&nbsp;</span><span class="str">'_model'</span><span class="pun">:</span><span class="pln">&nbsp;</span><span class="str">'Predator'</span><span class="pun">,</span><span class="pln">&nbsp;</span><span class="str">'_Laptop__price'</span><span class="pun">:</span><span class="pln">&nbsp;</span><span class="lit">5490</span><span class="pun">}</span></li></ol></pre></div></div><p><br></p></div></div>

In [240]:
class Laptop:
    def __init__(self, brand, model, price):
        self.brand = brand
        self._model = model
        self.__price = price
        
laptop = Laptop('Acer', 'Predator', 5490)
print(laptop.__dict__)

{'brand': 'Acer', '_model': 'Predator', '_Laptop__price': 5490}


<div class="instructions--content--1JI0g"><div class="udlite-heading-xl instructions--title--3vSDk" data-purpose="exercise-title">Exercise 2</div><div data-purpose="safely-set-inner-html:rich-text-viewer:html" class="udlite-text-sm rt-scaffolding"><p>A class called <em>Laptop </em>was implemented. Then, an instance of the <em>Laptop </em>class named <em>laptop </em>was created with the following arguments:</p><ul><li><p><code>'Acer'</code></p></li><li><p><code>'Predator'</code></p></li><li><p><code>5490</code></p></li></ul><p>In response, print the value for each instance attribute (on a separate line) of the <em>laptop</em> instance as shown below.</p><p><br></p><p><strong>Expected result:</strong></p><p><br></p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="pln">brand </span><span class="pun">-&gt;</span><span class="pln"> </span><span class="typ">Acer</span></li><li class="L1"><span class="pln">model </span><span class="pun">-&gt;</span><span class="pln"> </span><span class="typ">Predator</span></li><li class="L2"><span class="pln">price </span><span class="pun">-&gt;</span><span class="pln"> </span><span class="lit">5490</span></li></ol></pre></div></div><p><br></p></div></div>

In [250]:
class Laptop:

    def __init__(self, brand, model, price):
        self.brand = brand
        self._model = model
        self.__price = price

In [252]:
laptop = Laptop('Acer', 'Predator', 5490)
print(f'brand -> {laptop.brand}')
print(f'model -> {laptop._model}')
print(f'price -> {laptop._Laptop__price}')

brand -> Acer
model -> Predator
price -> 5490


In [ ]:
# class Laptop:

#     def __init__(self, brand, model, price):
#         self.brand = brand
#         self._model = model
#         self.__price = price
    
#     def display_attrs_with_values(self):
#         for attr, val in self.__dict__.items():
#             print(f'{attr} -> {val}')


# laptop = Laptop('Acer', 'Predator', 5490)
# laptop.display_attrs_with_values()

<div class="instructions--content--1JI0g"><div class="udlite-heading-xl instructions--title--3vSDk" data-purpose="exercise-title">Exercise 3</div><div data-purpose="safely-set-inner-html:rich-text-viewer:html" class="udlite-text-sm rt-scaffolding"><p>An implementation of the <em>Laptop </em>class is given. Implement a method in the <em>Laptop </em>class called <code>display_private_attrs()</code> that displays the names of all private attributes of the instance. Then create an instance with the given arguments:</p><ul><li><p><code>'Acer'</code></p></li><li><p><code>'Predator'</code></p></li><li><p><code>'AC-100'</code></p></li><li><p><code>5490</code></p></li><li><p><code>0.2</code></p></li></ul><p>and assign it to the variable <em>laptop</em>. In response, call <code>display_private_attrs()</code> on the <em>laptop </em>instance.</p><p><br></p><p><strong>Expected result:</strong></p><p><br></p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="typ">_Laptop__price</span></li><li class="L1"><span class="typ">_Laptop__margin</span></li></ol></pre></div></div><p><br></p></div></div>

In [274]:
# class Laptop:

#     def __init__(self, brand, model, code, price, margin):
#         self.brand = brand
#         self._model = model
#         self._code = code
#         self.__price = price
#         self.__margin = margin
        
#     def display_private_attrs(self):
#         for attr in self.__dict__.keys():
#             if attr.startswith('_Laptop__'):
#                 print(attr)
                
# laptop = Laptop('Acer', 'Predator', 'AX-100', 5490, 0.2)
# laptop.display_private_attrs()

_Laptop__price
_Laptop__margin


In [284]:
class Laptop:
 
    def __init__(self, brand, model, code, price, margin):
        self.brand = brand
        self._model = model
        self._code = code
        self.__price = price
        self.__margin = margin
 
    def display_private_attrs(self):
        for attr in self.__dict__:
            if attr.startswith(f'_{self.__class__.__name__}__'):
                print(attr)    
 
 
laptop = Laptop('Acer', 'Predator', 'AC-100', 5490, 0.2)
laptop.display_private_attrs()

_Laptop__price
_Laptop__margin


<div class="instructions--content--1JI0g"><div class="udlite-heading-xl instructions--title--3vSDk" data-purpose="exercise-title">Exercise 4</div><div data-purpose="safely-set-inner-html:rich-text-viewer:html" class="udlite-text-sm rt-scaffolding"><p>An implementation of the <em>Laptop </em>class is given. Implement a method called <code>display_protected_attrs()</code> in the <em>Laptop </em>class that displays the names of the protected attribute of the instance. Then create an instance with the given arguments:</p><ul><li><p><code>'Acer'</code></p></li><li><p><code>'Predator'</code></p></li><li><p><code>'AC-100'</code></p></li><li><p><code>5490</code></p></li><li><p><code>0.2</code></p></li></ul><p>and assign it to the variable <em>laptop</em>. In response, call <code>display_protected_attrs()</code> on the <em>laptop </em>instance.</p><p><br></p><p><strong>Expected result:</strong></p><p><br></p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="pln">_model</span></li><li class="L1"><span class="pln">_code</span></li></ol></pre></div></div><p><br></p></div></div>

In [290]:
class Laptop:
 
    def __init__(self, brand, model, code, price, margin):
        self.brand = brand
        self._model = model
        self._code = code
        self.__price = price
        self.__margin = margin
 
    def display_private_attrs(self):
        for attr in self.__dict__:
            if (not attr.startswith(f'_{self.__class__.__name__}__')) and (attr.startswith('_')):
                print(attr)    
 
 
laptop = Laptop('Acer', 'Predator', 'AC-100', 5490, 0.2)
laptop.display_private_attrs()

_model
_code


# Encapsulation

<div class="instructions--content--1JI0g"><div class="udlite-heading-xl instructions--title--3vSDk" data-purpose="exercise-title">Exercise 1</div><div data-purpose="safely-set-inner-html:rich-text-viewer:html" class="udlite-text-sm rt-scaffolding"><p>Implement a class called <em>Laptop </em>which in the <code>__init __()</code> method sets the value of the <em>price </em>protected attribute that stores the price of the laptop (without any validation). Then implement a method to read that attribute named <code>get_price()</code> and a method to modify that attribute named <code>set_price()</code> without validation as well.</p><p>Then create an instance of the <em>Laptop </em>class with a price of 3499 and follow these steps:</p><ul><li><p>using the <code>get_price()</code> method print the value of the <em>price </em>protected attribute to the console</p></li><li><p>using the <code>set_price()</code> method, set the value of the <em>price </em>protected attribute to 3999</p></li><li><p>using the <code>get_price()</code> method print the value of the <em>price </em>protected attribute to the console</p></li></ul><p><br></p><p><strong>Expected result:</strong></p><p><br></p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="lit">3499</span></li><li class="L1"><span class="lit">3999</span></li></ol></pre></div></div><p><br></p></div></div>

In [20]:
class Laptop:
    def __init__(self, price):
        self._price = price

    def get_price(self):
        return self._price
    
    def set_price(self, value):
        self._price = value
    
laptop = Laptop(3499)
print(laptop.get_price())
laptop.set_price(3999)
print(laptop.get_price())

3499
3999


<div class="instructions--content--1JI0g"><div class="udlite-heading-xl instructions--title--3vSDk" data-purpose="exercise-title">Exercise 2</div><div data-purpose="safely-set-inner-html:rich-text-viewer:html" class="udlite-text-sm rt-scaffolding"><p>A class called <em>Laptop </em>was implemented. Implement a method named <code>set_price()</code> to modify <em>price</em> attribute that validates the value. Validation checks:</p><ul><li><p>whether the value is an <code>int</code> or <code>float</code> type, if it is not raise a <code>TypeError</code> with the following message:<br><br></p></li></ul><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="str">'The price attribute must be an int or float type.'</span></li></ol></pre></div></div><ul><li><p>whether the value is positive, if it is not raise <code>ValueError</code> with the following message:<br><br></p></li></ul><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="str">'The price attribute must be a positive int or float value.'</span></li></ol></pre></div></div><p>Then create an instance of the <em>Laptop </em>class with a price of 3499 and try to set <code>'-3000'</code> to the price using <code>set_price()</code> method. If an error is raised, print the error message to the console. Use a <code>try ... except ...</code> clause in your solution.</p><p><br></p><p><strong>Expected result:</strong></p><p><br></p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="typ">The</span><span class="pln"> price attribute must be an </span><span class="kwd">int</span><span class="pln"> </span><span class="kwd">or</span><span class="pln"> </span><span class="kwd">float</span><span class="pln"> type</span><span class="pun">.</span></li></ol></pre></div></div><p><br></p></div></div>

In [49]:
class Laptop:

    def __init__(self, price):
        self._price = price

    def get_price(self):
        return self._price
    def set_price(self, value):
        if not isinstance(value, (int, float)):
            raise TypeError('The price attribute must be an int or float type.')
        
        if not value > 0:
            raise ValueError('The price attribute must be a positive int or float value.')
            
        self._price = value
               

In [48]:
laptop = Laptop(3499)
try:
    laptop.set_price("-3400")
except TypeError as error:
    print(error)
except ValueError as error:
    print(error)

The price attribute must be a positive int or float value.


<div class="instructions--content--1JI0g"><div class="udlite-heading-xl instructions--title--3vSDk" data-purpose="exercise-title">Exercise 4</div><div data-purpose="safely-set-inner-html:rich-text-viewer:html" class="udlite-text-sm rt-scaffolding"><p>A class called <em>Laptop </em>was implemented. </p><p>Add validation of the <em>price </em>attribute also at the stage of creating the instance (in <code>__init__()</code> method).</p><p>Then try to create an instance of the <em>Laptop </em>class with a price of -3499. If an error is raised, print the error message to the console. Use a <code>try ... except ...</code> clause in your solution.</p><p><br></p><p><strong>Expected result:</strong></p><p><br></p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="typ">The</span><span class="pln"> price attribute must be a positive </span><span class="kwd">int</span><span class="pln"> </span><span class="kwd">or</span><span class="pln"> </span><span class="kwd">float</span><span class="pln"> value</span><span class="pun">.</span></li></ol></pre></div></div><p><br></p></div></div>

In [61]:
class Laptop:

    def __init__(self, price):
        self.set_price(price)

    def get_price(self):
        return self._price
    def set_price(self, value):
        if not isinstance(value, (int, float)):
            raise TypeError('The price attribute must be an int or float type.')
        
        if not value > 0:
            raise ValueError('The price attribute must be a positive int or float value.')
            
        self._price = value

In [62]:
try:
    laptop = Laptop(-3499)
except TypeError as error:
    print(error)
except ValueError as error:
    print(error)

The price attribute must be a positive int or float value.


## Jak zrobić pole tylko do odczytu - funkcja <code>property<code\>

<div class="instructions--content--1JI0g"><div class="udlite-heading-xl instructions--title--3vSDk" data-purpose="exercise-title">Exercise 5</div><div data-purpose="safely-set-inner-html:rich-text-viewer:html" class="udlite-text-sm rt-scaffolding"><p>Implement a class named <em>Person </em>that has one protected instance attribute named <em>first_name</em>. Next, implement a method <code>get_first_name()</code> which reads the value of the <em>first_name </em>protected attribute. Then, using the <code>get_first_name()</code> method and the <em>property </em>class (do it in the standard way) create a property named <em>first_name </em>(read-only property).</p><p>Create an instance of the <em>Person </em>class and set the <em>first_name </em>attribute to <code>'John'</code>. Print the value of the <em>first_name </em>attribute of this instance to the console.</p><p><br></p><p><strong>Expected result:</strong></p><p><br></p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="typ">John</span></li></ol></pre></div></div><p><br></p></div></div>

In [115]:
class Person:
    def __init__(self, first_name):
        self._first_name = first_name
        
    def get_first_name(self):
        return self._first_name
    
    first_name = property(get_first_name, )
    # first_name = property(fget=get_first_name)

person = Person("John")

print(person.first_name)

John


<div class="instructions--content--1JI0g"><div class="udlite-heading-xl instructions--title--3vSDk" data-purpose="exercise-title">Exercise 6</div><div data-purpose="safely-set-inner-html:rich-text-viewer:html" class="udlite-text-sm rt-scaffolding"><p>Implement a class named <em>Person </em>that has two instance protected attributes named <em>first_name </em>and <em>last_name</em>, respectively. Then implement methods named <code>get_first_name()</code> and <code>get_last_name()</code>, which reads the protected attributes: <em>first_name </em>and <em>last_name</em>. </p><p>Then, using the <code>get_first_name()</code> and <code>get_last_name()</code> methods and the <em>property </em>class (do it in the standard way) create two properties named <em>first_name </em>and <em>last_name </em>(read-only properties).</p><p>Create an instance of the <em>Person </em>class and set the following attributes:</p><ul><li><p><em>first_name</em> to the value <code>'John'</code></p></li><li><p><em>last_name </em>to the value <code>'Dow'</code></p></li></ul><p>Print the value of the <em>first_name </em>and <em>last_name </em>attribute of this instance to the console.</p><p><br></p><p><strong>Expected result:</strong></p><p><br></p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="typ">John</span></li><li class="L1"><span class="typ">Dow</span></li></ol></pre></div></div><p><br></p></div></div>

In [127]:
class Person:
    def __init__(self, first_name, last_name):
        self._first_name = first_name
        self._last_name = last_name
        
    def get_first_name(self):
        return self._first_name
    
    def get_last_name(self):
        return self._last_name
    
    first_name = property(fget=get_first_name)
    last_name = property(fget=get_last_name)

In [130]:
person = Person('John', 'Dow')
print(person.first_name)
print(person.last_name)

John
Dow


<div class="instructions--content--1JI0g"><div class="udlite-heading-xl instructions--title--3vSDk" data-purpose="exercise-title">Exercise 7</div><div data-purpose="safely-set-inner-html:rich-text-viewer:html" class="udlite-text-sm rt-scaffolding"><p>Implement a class named <em>Person </em>that has one protected attribute <em>first_name</em>. Next, implement a method <code>get_first_name()</code> which reads the value of the <em>first_name </em>protected attribute. Declare a method&nbsp; <code>set_first_name()</code> that allows you to modify the value of the <em>first_name </em>protected attribute (without validation).</p><p>Then, using the <code>get_first_name()</code>, <code>set_first_name()</code> methods and the <em>property </em>class (do it in the standard way) create a property called <em>first_name </em>(property to read and modify).</p><p>Create an instance of the <em>Person </em>class and set the <em>first_name </em>attribute to <code>'John'</code>. Then, using the <code>set_first_name()</code> method, set new value <code>'Mike'</code>. </p><p>In response, print the value of the <em>first_name</em> attribute to the console.</p><p><br></p><p><strong>Expected result:</strong></p><p><br></p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="typ">Mike</span></li></ol></pre></div></div><p><br></p></div></div>

In [140]:
class Person:
    def __init__(self, first_name):
        self._first_name = first_name
        
    def get_first_name(self):
        return self._first_name
    
    def set_first_name(self, name):
        self._first_name = name
    
    first_name = property(fget=get_first_name, fset=set_first_name)

person = Person('John')
person.set_first_name('Mike')
print(person.first_name)

Mike


<div class="instructions--content--1JI0g"><div class="udlite-heading-xl instructions--title--3vSDk" data-purpose="exercise-title">Exercise 8</div><div data-purpose="safely-set-inner-html:rich-text-viewer:html" class="udlite-text-sm rt-scaffolding"><p>Implement a class named <em>Person </em>that has two protected attributes: <em>first_name </em>and <em>last_name</em>, respectively. Next implement methods named <code>get_first_name()</code>, <code>set_first_name()</code>, <code>get_last_name()</code>, <code>set_last_name()</code>, which allows you to read and modify the value of the <em>first_name </em>and <em>last_name </em>protected attributes.</p><p><br></p><p>Then, using the methods <code>get_first_name()</code>, <code>set_first_name()</code>, <code>get_last_name()</code>, <code>set_last_name()</code> and the <em>property </em>class (do it in the standard way) create properties: <em>first_name </em>and <em>last_name </em>(properties to read and modify).</p><p>Create an instance of the <em>Person </em>class with the following values:</p><ul><li><p><code>first_name = 'John'</code></p></li><li><p><code>last_name = 'Dow'</code></p></li></ul><p>Then print the values of these attributes to the console as shown below. </p><p>Using the dot notation, modify the attribute values for this instance, respectively:</p><ul><li><p><em>first_name</em> to the value <code>'Tom'</code></p></li><li><p><em>last_name </em>to the value <code>'Smith'</code></p></li></ul><p>In response, print the <code>__dict__</code> attribute of the created instance to the console.</p><p><br></p><p><strong>Expected result:</strong></p><p><br></p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="typ">John</span></li><li class="L1"><span class="typ">Dow</span></li><li class="L2"><span class="pun">{</span><span class="str">'_first_name'</span><span class="pun">:</span><span class="pln">&nbsp;</span><span class="str">'Tom'</span><span class="pun">,</span><span class="pln">&nbsp;</span><span class="str">'_last_name'</span><span class="pun">:</span><span class="pln">&nbsp;</span><span class="str">'Smith'</span><span class="pun">}</span></li></ol></pre></div></div><p><br></p></div></div>

In [152]:
class Person:
    def __init__(self, first_name, last_name):
        self._first_name = first_name
        self._last_name = last_name
        
    def get_first_name(self):
        return self._first_name
    
    def set_first_name(self, name):
        self._first_name = name
    
    def get_last_name(self):
        return self._last_name
    
    def set_last_name(self, name):
        self._last_name = name
    
    first_name = property(fget=get_first_name, fset=set_first_name)
    last_name = property(fget=get_last_name, fset=set_last_name)

person = Person('John', 'Dow')
print(person.first_name)
print(person.last_name)
person.set_first_name('Tom')
person.set_last_name('Smith')
print(person.__dict__)

John
Dow
{'_first_name': 'Tom', '_last_name': 'Smith'}


<div class="instructions--content--1JI0g"><div class="udlite-heading-xl instructions--title--3vSDk" data-purpose="exercise-title">Exercise 9</div><div data-purpose="safely-set-inner-html:rich-text-viewer:html" class="udlite-text-sm rt-scaffolding"><p>A class named <em>Person </em>was implemented.</p><p>Implement the <code>del_first_name()</code> method to remove the <em>first_name </em>protected attribute.</p><p>Then, using the methods <code>get_first_name()</code>, <code>set_first_name()</code>, <code>del_first_name()</code> and the <em>property </em>class (do this in the standard way) create property named <em>first_name </em>(properties to read, modify and delete).</p><p>Create an instance of the <em>Person </em>class named <em>person </em>and assign the value <code>'Tom'</code> to <em>first_name</em>. Use the <code>del_first_name()</code> method to delete the <em>first_name </em>attribute of the person instance. Display the <code>__dict__</code> attribute of the <em>person </em>instance to the console.</p><p><br></p><p><strong>Expected result:</strong></p><p><br></p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="pun">{}</span></li></ol></pre></div></div><p><br></p></div></div>

In [154]:
class Person:
    def __init__(self, first_name):
        self._first_name = first_name
        
    def get_first_name(self):
        return self._first_name
    
    def set_first_name(self, name):
        self._first_name = name
    
    def del_first_name(self):
        del self._first_name
    
    first_name = property(fget=get_first_name, fset=set_first_name, fdel=del_first_name)

person = Person('John')
person.del_first_name()
print(person.__dict__)

{}


## Dekorator <code>property<code\>

<div class="instructions--content--1JI0g"><div class="udlite-heading-xl instructions--title--3vSDk" data-purpose="exercise-title">Exercise 10</div><div data-purpose="safely-set-inner-html:rich-text-viewer:html" class="udlite-text-sm rt-scaffolding"><p>Implement a class named <em>Pet </em>that has one protected instance attribute <em>name</em>. Then implement a method <code>name()</code> which reads the value of the protected <em>name </em>attribute. </p><p>Create a property <em>name </em>(read-only) using the <code>@property</code> decorator.</p><p>Create an instance of the <em>Pet </em>class named <em>pet</em> and set <em>name </em>attribute to <code>'Max'</code>. In response, print the contents of the <code>__dict__</code> attribute of this<em> </em>instance.</p><p><br></p><p><strong>Expected result:</strong></p><p><br></p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="pun">{</span><span class="str">'_name'</span><span class="pun">:</span><span class="pln">&nbsp;</span><span class="str">'Max'</span><span class="pun">}</span></li></ol></pre></div></div><p><br></p></div></div>

In [16]:
class Pet:
    def __init__(self, name):
        self._name = name
        
    @property
    def name(self):
        return self._name
    @name.setter
    def name(self, name):
        self._name = name

pet = Pet('Max')
print(pet.__dict__)

{'_name': 'Max'}


In [120]:
class Pet:
 
    def __init__(self, name):
        self._name = name
 
    @property
    def name(self):
        return self._name
 
        
pet = Pet('Max')
print(pet.__dict__)

{'_name': 'Max'}


<div class="instructions--content--1JI0g"><div class="udlite-heading-xl instructions--title--3vSDk" data-purpose="exercise-title">Exercise 11</div><div data-purpose="safely-set-inner-html:rich-text-viewer:html" class="udlite-text-sm rt-scaffolding"><p>Implement a class named <em>Pet </em>that has two protected instance attributes: name and <em>age</em>, respectively. Next implement the methods: <code>name()</code> and <code>age()</code>, which reads the value of the protected attributes: <em>name </em>and <em>age</em>. </p><p>Using the <code>@property</code> decorator, create properties: <em>name</em> and <em>age</em>, respectively (read-only properties).</p><p>Create an instance of the <em>Pet </em>class named <em>pet </em>and set the <em>name </em>attribute to <code>'Max'</code> and <em>age </em>to <code>5</code>. </p><p>In response. print the contents of the <code>__dict__</code> attribute of <em>pet </em>instance to the console.</p><p><br></p><p><strong>Expected result:</strong></p><p><br></p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="pun">{</span><span class="str">'_name'</span><span class="pun">:</span><span class="pln"> </span><span class="str">'Max'</span><span class="pun">,</span><span class="pln"> </span><span class="str">'_age'</span><span class="pun">:</span><span class="pln"> </span><span class="lit">5</span><span class="pun">}</span></li></ol></pre></div></div><p><br></p></div></div>

In [22]:
class Pet:
    def __init__(self, name, age):
        self._name = name
        self._age = age
        
    @property
    def name(self):
        return self._name
    
    @property
    def age(self):
        return self._age

    
pet = Pet('Max', 5)
print(pet.__dict__)

{'_name': 'Max', '_age': 5}


<div class="instructions--content--1JI0g"><div class="udlite-heading-xl instructions--title--3vSDk" data-purpose="exercise-title">Exercise 12</div><div data-purpose="safely-set-inner-html:rich-text-viewer:html" class="udlite-text-sm rt-scaffolding"><p>Implement a class named <em>Pet </em>that has one protected instance attribute <em>name</em>. Then, using the <code>@property</code> decorator, create a property <em>name </em>(property to read and modify, without validation).</p><p>Create an instance of the <em>Pet </em>class named <em>pet</em> and set the <em>name </em>attribute to <code>'Max'</code>. Then, using dot notation, modify the value of the <em>name </em>attribute to <code>'Oscar'</code>. </p><p>In response, print the contents of the <code>__dict__ </code>attribute of this instance to the console.</p><p><br></p><p><strong>Expected result:</strong></p><p><br></p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="pun">{</span><span class="str">'_name'</span><span class="pun">:</span><span class="pln">&nbsp;</span><span class="str">'Oscar'</span><span class="pun">}</span></li></ol></pre></div></div><p><br></p></div></div>

In [30]:
class Pet:
    def __init__(self, name):
        self._name = name
        
    @property
    def name(self):
        return self._name
    @name.setter
    def name(self, value):
        self._name = value
    

pet = Pet('Max')
pet.name = 'Oscar'
print(pet.__dict__)

{'_name': 'Oscar'}


<div class="instructions--content--1JI0g"><div class="udlite-heading-xl instructions--title--3vSDk" data-purpose="exercise-title">Exercise 13</div><div data-purpose="safely-set-inner-html:rich-text-viewer:html" class="udlite-text-sm rt-scaffolding"><p>Implement a class named <em>Pet </em>that has two protected instance attributes: <em>name </em>and <em>age</em>, respectively. Then, using the <code>@property</code> decorator, create properties: <em>name </em>and <em>age</em>, respectively (properties to read and modify, without validation).</p><p>Create an instance of the <em>Pet </em>class with the name <em>pet </em>and attributes:</p><ul><li><p><code>name = 'Max'</code></p></li><li><p><code>age = 5</code></p></li></ul><p>Print the <code>__dict__</code> attribute of the <em>pet </em>instance to the console. Then modify the attributes using the dot notation:</p><ul><li><p><em>name </em>to the value <code>'Tom'</code></p></li><li><p><em>age</em> to the value <code>8</code></p></li></ul><p>Again, print the <code>__dict__</code> attribute of the <em>pet</em> instance to the console again.</p><p><br></p><p><strong>Expected result:</strong></p><p><br></p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="pun">{</span><span class="str">'_name'</span><span class="pun">:</span><span class="pln">&nbsp;</span><span class="str">'Max'</span><span class="pun">,</span><span class="pln">&nbsp;</span><span class="str">'_age'</span><span class="pun">:</span><span class="pln">&nbsp;</span><span class="lit">5</span><span class="pun">}</span></li><li class="L1"><span class="pun">{</span><span class="str">'_name'</span><span class="pun">:</span><span class="pln">&nbsp;</span><span class="str">'Tom'</span><span class="pun">,</span><span class="pln">&nbsp;</span><span class="str">'_age'</span><span class="pun">:</span><span class="pln">&nbsp;</span><span class="lit">8</span><span class="pun">}</span></li></ol></pre></div></div><p><br></p></div></div>

In [32]:
class Pet:
    def __init__(self, name, age):
        self._name = name
        self._age = age
        
    @property
    def name(self):
        return self._name
    @name.setter
    def name(self, value):
        self._name = value
        
    @property
    def age(self):
        return self._age
    @age.setter
    def age(self, value):
        self._age = value
    

pet = Pet('Max', 5)
print(pet.__dict__)
pet.name = 'Tom'
pet.age = 8
print(pet.__dict__)

{'_name': 'Max', '_age': 5}
{'_name': 'Tom', '_age': 8}


<div class="instructions--content--1JI0g"><div class="udlite-heading-xl instructions--title--3vSDk" data-purpose="exercise-title">Exercise 14</div><div data-purpose="safely-set-inner-html:rich-text-viewer:html" class="udlite-text-sm rt-scaffolding"><p>A class called <em>Pet </em>is implemented that has two properties: <em>name</em> and <em>age </em>(see below). Add validation to the <em>age </em>property at the stage of object creation and attribute modification:</p><ul><li><p>the value of the <em>age </em>attribute must be an <code>int</code> type, otherwise raise a <code>TypeError</code> with the following message:</p><p><br></p></li></ul><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="str">'The value of age must be of type int.'</span></li></ol></pre></div></div><ul><li><p>the value of the <em>age </em>attribute must be positive, otherwise raise <code>ValueError</code> with the following message:<br><br></p></li></ul><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="str">'The value of age must be a positive integer.'</span></li></ol></pre></div></div><p>Then try to create an instance of the <em>Pet </em>class named <em>pet</em> and set the following values:</p><ul><li><p><code>'Max'</code></p></li><li><p><code>'seven'</code></p></li></ul><p>If there is an error, print an error message to the console. Use a <code>try ... except ...</code> clause in your solution.</p><p><br></p><p><strong>Expected result:</strong></p><p><br></p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="typ">The</span><span class="pln">&nbsp;value&nbsp;of&nbsp;age&nbsp;must&nbsp;be&nbsp;of&nbsp;type&nbsp;</span><span class="kwd">int</span><span class="pun">.</span></li></ol></pre></div></div><p><br></p></div></div>

In [123]:
class Pet:

    def __init__(self, name, age):
        self._name = name
        self.age = age

    @property
    def name(self):
        return self._name

    @name.setter
    def name(self, value):
            self._name = value

    @property
    def age(self):
        return self._age
  
    @age.setter
    def age(self, value):
        if isinstance(value, int):
            if value >= 0:
                self._age = value
            else:
                raise ValueError('The value of age must be a positive integer.')
        else:
            raise TypeError('The value of age must be of type int.')

In [124]:
try:
    pet = Pet('Max', 'seven')
except TypeError as error:
    print(error)
except ValueError as error:
    print(error)

The value of age must be of type int.


<div class="instructions--content--1JI0g"><div class="udlite-heading-xl instructions--title--3vSDk" data-purpose="exercise-title">Exercise 15</div><div data-purpose="safely-set-inner-html:rich-text-viewer:html" class="udlite-text-sm rt-scaffolding"><p>A class called <em>Pet </em>is implemented that has two properties: <em>name </em>and <em>age </em>(see below). Create an instance of the <em>Pet </em>class with the name <em>pet </em>and attribute values respectively:</p><ul><li><p><code>'Max'</code></p></li><li><p><code>7</code></p></li></ul><p>Then try to modify the value of the <em>age </em>attribute to -10. If there is an error, print this error message to the console. Use a <code>try ... except ...</code> clause in your solution.</p><p><br></p><p><strong>Expected result:</strong></p><p><br></p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="typ">The</span><span class="pln"> value of age must be a positive integer</span><span class="pun">.</span></li></ol></pre></div></div><p><br></p></div></div>

In [116]:
class Pet:

    def __init__(self, name, age):
        self._name = name
        self.age = age

    @property
    def name(self):
        return self._name

    @name.setter
    def name(self, value):
            self._name = value

    @property
    def age(self):
        return self._age
  
    @age.setter
    def age(self, value):
        if isinstance(value, int):
            if value >= 0:
                self._age = value
            else:
                raise ValueError('The value of age must be a positive integer.')
        else:
            raise TypeError('The value of age must be of type int.')

In [117]:
try:
    pet = Pet('Max', 7)
except TypeError as error:
    print(error)
except ValueError as error:
    print(error)
    
try:
    pet.age = -10
except TypeError as error:
    print(error)
except ValueError as error:
    print(error)

The value of age must be a positive integer.


<div class="instructions--content--1JI0g"><div class="udlite-heading-xl instructions--title--3vSDk" data-purpose="exercise-title">Exercise 16</div><div data-purpose="safely-set-inner-html:rich-text-viewer:html" class="udlite-text-sm rt-scaffolding"><p>Implement a class named <em>TechStack </em>that has one protected instance attribute named <em>tech_names</em>. Then, using the <code>@property</code> decorator, create a property named <em>tech_names </em>(read, modify, and delete property, without validation). </p><p>Create an instance of the class named <em>tech_stack</em> and the <em>tech_names </em>attribute value:</p><ul><li><p><code>'python,java,sql'</code></p></li></ul><p>Print the content of the <em>tech_names </em>attribute. Then, modify this attribute to value:</p><ul><li><p><code>'python,sql'</code></p></li></ul><p>Also print the contents of the <em>tech_names </em>attribute to the console. </p><p>Remove the <em>tech_names </em>attribute of the <em>tech_stack </em>instance.</p><p>Print the contents of the <code>__dict__</code> attribute of the <em>tech_stack </em>instance to the console.</p><p><br></p><p><strong>Expected result:</strong></p><p><br></p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="pln">python</span><span class="pun">,</span><span class="pln">java</span><span class="pun">,</span><span class="pln">sql</span></li><li class="L1"><span class="pln">python</span><span class="pun">,</span><span class="pln">sql</span></li><li class="L2"><span class="pun">{}</span></li></ol></pre></div></div><p><br></p></div></div>

In [148]:
class TechStack:
    def __init__(self, tech_names):
        self._tech_names = tech_names
        
    @property
    def tech_names(self):
        return self._tech_names
    
    @tech_names.setter
    def tech_names(self, value):
        self._tech_names = value
    
    @tech_names.getter
    def tech_names(self):
        return self._tech_names  
    
    @tech_names.deleter
    def tech_names(self):
        del self._tech_names     

In [153]:
tech_stack = TechStack('python,java,sql')
print(tech_stack.tech_names)
tech_stack.tech_names = 'python,sql'
print(tech_stack.tech_names)
del tech_stack.tech_names
print(tech_stack.__dict__)

python,java,sql
python,sql
{}


<div class="instructions--content--1JI0g"><div class="udlite-heading-xl instructions--title--3vSDk" data-purpose="exercise-title">Exercise 17</div><div data-purpose="safely-set-inner-html:rich-text-viewer:html" class="udlite-text-sm rt-scaffolding"><p>Implement a class <em>Game </em>that has a property named <em>level </em>(read and modify property, defaults to 0). The value of the <em>level </em>attribute should be an integer in the range <code>[0, 100]</code>. Add validation at the instance creation and attribute modification stage. If the value is not of the <code>int</code> type, raise a <code>TypeError</code> with the following message:<br><br></p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="str">'The value of level must be of type int.'</span></li></ol></pre></div></div><p>If the value is outside the range <code>[0, 100]</code>, set the exceeded boundary value (0 or 100 respectively). Then create a list called <em>games </em>consisting of four instances of the <em>Game </em>class:</p><p><br></p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="pln">games </span><span class="pun">=</span><span class="pln"> </span><span class="pun">[</span><span class="typ">Game</span><span class="pun">(),</span><span class="pln"> </span><span class="typ">Game</span><span class="pun">(</span><span class="lit">10</span><span class="pun">),</span><span class="pln"> </span><span class="typ">Game</span><span class="pun">(-</span><span class="lit">10</span><span class="pun">),</span><span class="pln"> </span><span class="typ">Game</span><span class="pun">(</span><span class="lit">120</span><span class="pun">)]</span></li></ol></pre></div></div><p>Iterate through the <em>games </em>list and print the value of the <em>level </em>attribute for each instance.</p><p><br></p><p><strong>Expected result:</strong></p><p><br></p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="lit">0</span></li><li class="L1"><span class="lit">10</span></li><li class="L2"><span class="lit">0</span></li><li class="L3"><span class="lit">100</span></li></ol></pre></div></div><p><br></p></div></div>

In [163]:
class Game:
    def __init__(self, level = None):
        # self.level = level
        self.level = level if level else 0
        
    @property
    def level(self):
        return self._level
    
    @level.setter
    def level(self, value):
        if not isinstance(value, int):
            raise TypeError('The value of level must be of type int.')
        if value < 0:
            value = 0
        if value > 100:
            value = 100
        
        self._level = value

In [164]:
games = [Game(), Game(10), Game(-10), Game(120)]

In [165]:
for game in games:
    try:
        print(game.level)
    except TypeError as error:
        print(error)        

0
10
0
100


# Computed Attributes

<div class="instructions--content--1JI0g"><div class="udlite-heading-xl instructions--title--3vSDk" data-purpose="exercise-title">Exercise 1</div><div data-purpose="safely-set-inner-html:rich-text-viewer:html" class="udlite-text-sm rt-scaffolding"><p>Implement a class named <em>Circle </em>that will have the protected instance attribute <em>radius</em> - the radius of the circle (readable and modifiable property). Use the <code>@property</code> decorator.</p><p>Then create an instance named <em>circle </em>with <code>radius=3</code>. </p><p>In response, display the <code>__dict__</code> attribute of <em>circle </em>instance.</p><p><br></p><p><strong>Expected result:</strong></p><p><br></p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="pun">{</span><span class="str">'_radius'</span><span class="pun">:</span><span class="pln">&nbsp;</span><span class="lit">3</span><span class="pun">}</span></li></ol></pre></div></div><p><br></p></div></div>

In [2]:
class Circle:
    def __init__(self, radius):
        self.radius = radius
        
    @property
    def radius(self):
        return self._radius
    
    @radius.setter
    def radius(self, radius):
        self._radius = radius
    
    @radius.getter
    def radius(self):
        return self._radius
        

In [10]:
circle = Circle(3)
print(circle.__dict__)

{'_radius': 3}


<div class="instructions--content--1JI0g"><div class="udlite-heading-xl instructions--title--3vSDk" data-purpose="exercise-title">Exercise 2</div><div data-purpose="safely-set-inner-html:rich-text-viewer:html" class="udlite-text-sm rt-scaffolding"><p>A class named <em>Circle </em>is given. Add a property called <em>area </em>(read-only) to the class that calculates the <em>area </em>of a circle with a given <em>radius</em>. This<em> </em>property should only be computed <strong>at first reading or after modifying the <em>radius </em>attribute</strong>. To do this, also modify the way of setting the value of the <em>radius </em>attribute in the <code>__init __()</code> method. Make sure that the value of the <em>area </em>attribute is recalculated after changing the <em>radius </em>attribute.</p><p>Then create an instance named <em>circle </em>with <code>radius=3</code>. </p><p>In response, display the value of the <em>area </em>attribute to the console (round the result to four decimal places).</p><p><br></p><p><strong>Expected result:</strong></p><p><br></p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="lit">28.2743</span></li></ol></pre></div></div><p><br></p></div></div>

In [17]:
# import math


# class Circle:

#     def __init__(self, radius):
#         self.radius = radius

#     @property
#     def radius(self):
#         return self._radius

#     @radius.setter
#     def radius(self, value):
#         self._radius = value
    
#     @property
#     def area(self):
#         return area
    
#     @area.getter
#     def area(self):
#         area = round(math.pi*self.radius*self.radius,4)
#         return area
    
# circle = Circle(3)
# print(circle.area)

28.2743


In [20]:
import math
 
 
class Circle:
    def __init__(self, radius):
        self.radius = radius
        self._area = None
 
    @property
    def radius(self):
        return self._radius
 
    @radius.setter
    def radius(self, value):
        self._radius = value
        self._area = None
 
    @property
    def area(self):
        if self._area is None:
            self._area = math.pi * self._radius * self._radius
        return self._area
 
 
circle = Circle(3)
print(f'{circle.area:.4f}')

28.2743


<div class="instructions--content--1JI0g"><div class="udlite-heading-xl instructions--title--3vSDk" data-purpose="exercise-title">Exercise 3</div><div data-purpose="safely-set-inner-html:rich-text-viewer:html" class="udlite-text-sm rt-scaffolding"><p>A class named <em>Circle </em>is given. Add a property to the class called <em>perimeter </em>(read-only) that calculates the length of circle with a given <em>radius</em>. This property should be computed only <strong>at the first reading or after modifying the radius attribute</strong>. To do this, also modify the way of setting the value of the <em>radius </em>attribute in the <code>__init __()</code> method. Make sure that the value of the perimeter attribute is recalculated when the <em>radius </em>attribute is changed.</p><p>Then create an instance named <em>circle </em>with <code>radius=3</code>. </p><p>In response, display the value of the <em>perimeter </em>attribute to the console (round the result to four decimal places).</p><p><br></p><p><strong>Expected result:</strong></p><p><br></p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="lit">18.8496</span></li></ol></pre></div></div><p><br></p></div></div>

In [26]:
import math


class Circle:
    def __init__(self, radius):
        self.radius = radius
        self._area = None
        self._perimeter = None

    @property
    def radius(self):
        return self._radius

    @radius.setter
    def radius(self, value):
        self._radius = value
        self._area = None
        self._perimeter = None

    @property
    def area(self):
        if self._area is None:
            self._area = math.pi * self._radius * self._radius
        return self._area
    
    @property
    def perimeter(self):
        if self._perimeter is None:
            self._perimeter = 2 * math.pi * self._radius
        return self._perimeter
    


In [30]:
circle = Circle(3)
print(f'{circle.perimeter:.4f}')

18.8496


<div class="instructions--content--1JI0g"><div class="udlite-heading-xl instructions--title--3vSDk" data-purpose="exercise-title">Exercise 4</div><div data-purpose="safely-set-inner-html:rich-text-viewer:html" class="udlite-text-sm rt-scaffolding"><p>Implement a class named <em>Rectangle </em>which will have the following properties:</p><ul><li><p><em>width</em></p></li><li><p><em>height</em></p></li></ul><p>The width and height of the rectangle, respectively (for reading and for modification). Also add a property named <em>area </em>that stores the area of the rectangle (read-only). This property should be computed only at the first reading or after modifying any of the rectangle sides. Skip attribute validation.</p><p>Then create an instance named <em>rectangle</em> with a width = 3 and a height = 4 and print the information about the <em>rectangle </em>instance to the console as shown below.</p><p><br></p><p><strong>Expected result:</strong></p><p><br></p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="pln">width</span><span class="pun">:</span><span class="pln"> </span><span class="lit">3</span><span class="pun">,</span><span class="pln"> height</span><span class="pun">:</span><span class="pln"> </span><span class="lit">4</span><span class="pln"> </span><span class="pun">-&gt;</span><span class="pln"> area</span><span class="pun">:</span><span class="pln"> </span><span class="lit">12</span></li></ol></pre></div></div><p><br></p></div></div>

In [16]:
class Rectangle:
    
    def __init__(self, width, height):
        self.width = width
        self.height = height
        self._area = None
        
    @property
    def width(self):
        return self._width
 
    @width.setter
    def width(self, value):
        self._area = None
        self._width = value
    
    @property
    def height(self):
        return self._height
    
    @height.setter
    def height(self, value):
        self._area = None
        self._height = value
          
    @property
    def area(self):
        if self._area is None:
            self._area = self._height * self._width
        return self._area
    
    
        

In [19]:
rectangle = Rectangle(3, 4)
print(f'width: {rectangle.width}, height: {rectangle.height} -> area: {rectangle.area}')

width: 3, height: 4 -> area: 12


<div class="instructions--content--1JI0g"><div class="udlite-heading-xl instructions--title--3vSDk" data-purpose="exercise-title">Exercise 5</div><div data-purpose="safely-set-inner-html:rich-text-viewer:html" class="udlite-text-sm rt-scaffolding"><p>A class called <em>Rectangle </em>is given. Add a property called <em>perimeter</em>, which stores the perimeter of the rectangle (read only). The <em>perimeter </em>property should be computed only at the first reading or after modifying any of the sides of the rectangle. Skip attribute validation.</p><p>Then create an instance named <em>rectangle </em>with a width = 3 and a height = 4 and print the information about the <em>rectangle </em>instance to the console as shown below.</p><p><br></p><p><strong>Expected result:</strong></p><p><br></p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="pln">width</span><span class="pun">:</span><span class="pln"> </span><span class="lit">3</span><span class="pun">,</span><span class="pln"> height</span><span class="pun">:</span><span class="pln"> </span><span class="lit">4</span><span class="pln"> </span><span class="pun">-&gt;</span><span class="pln"> perimeter</span><span class="pun">:</span><span class="pln"> </span><span class="lit">14</span></li></ol></pre></div></div><p><br></p></div></div>

In [32]:
class Rectangle:

    def __init__(self, width, height):
        self.width = width
        self.height = height
        self._area = None
        self._perimeter = None

    @property
    def width(self):
        return self._width

    @width.setter
    def width(self, value):
        self._width = value
        self._area = None
        self._perimeter = None

    @property
    def height(self):
        return self._height

    @height.setter
    def height(self, value):
        self._height = value
        self._area = None
        self._perimeter = None

    @property
    def area(self):
        if self._area is None:
            self._area = self._width * self._height
        return self._area
    
    @property
    def perimeter(self):
        if self._perimeter is None:
            self._perimeter = 2 * (self._width + self._height)
        return self._perimeter

In [33]:
rectangle = Rectangle(3,4)

In [34]:
rectangle.area

12

# Class method - decorator @classmethod

<div class="instructions--content--1JI0g"><div class="udlite-heading-xl instructions--title--3vSDk" data-purpose="exercise-title">Exercise 1</div><div data-purpose="safely-set-inner-html:rich-text-viewer:html" class="udlite-text-sm rt-scaffolding"><p>Using the <em>classmethod </em>class (do it in the standard way) implement a class named <em>Person </em>that has a class method named <code>show_details()</code> which displays the following text to the console:</p><p><br></p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="str">'Running&nbsp;from&nbsp;Person&nbsp;class.'</span></li></ol></pre></div></div><p>Try to pass the class name using the appropriate attribute of the <em>Person </em>class. </p><p>In response, call the <code>show_details()</code> class method.</p><p><br></p><p><strong>Expected result:</strong></p><p><br></p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="typ">Running</span><span class="pln">&nbsp;</span><span class="kwd">from</span><span class="pln">&nbsp;</span><span class="typ">Person</span><span class="pln">&nbsp;</span><span class="kwd">class</span><span class="pun">.</span></li></ol></pre></div></div><p><br></p></div></div>

In [44]:
class Person:
    
    def show_details(cls):
        print(f'Running from {cls.__name__} class')
        
    show_details = classmethod(show_details)

Person.show_details()

<div class="instructions--content--1JI0g"><div class="udlite-heading-xl instructions--title--3vSDk" data-purpose="exercise-title">Exercise 2</div><div data-purpose="safely-set-inner-html:rich-text-viewer:html" class="udlite-text-sm rt-scaffolding"><p>Using the <code>@classmethod</code> decorator, implement a class named <em>Container </em>which has a class method named <code>show_details()</code> displaying the following text to the console:</p><p><br></p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="str">'Running&nbsp;from&nbsp;Container&nbsp;class.'</span></li></ol></pre></div></div><p>Try to pass the class name using the appropriate attribute of the <em>Container </em>class.</p><p> In response, call the <code>show_details()</code> class method.</p><p><br></p><p><strong>Expected result:</strong></p><p><br></p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="typ">Running</span><span class="pln">&nbsp;</span><span class="kwd">from</span><span class="pln">&nbsp;</span><span class="typ">Container</span><span class="pln">&nbsp;</span><span class="kwd">class</span><span class="pun">.</span></li></ol></pre></div></div><p><br></p></div></div>

In [47]:
class Container:
    
    @classmethod
    def show_details(cls):
        print(f'Running from {cls.__name__} class.')
        
Container.show_details()

Running from Container class.


<div class="instructions--content--1JI0g"><div class="udlite-heading-xl instructions--title--3vSDk" data-purpose="exercise-title">Exercise 3</div><div data-purpose="safely-set-inner-html:rich-text-viewer:html" class="udlite-text-sm rt-scaffolding"><p>The <em>Container </em>class is given. Create an instance of this class named <em>container </em>and call the <code>show_details()</code> method from this instance.</p><p><br></p><p><strong>Expected result:</strong></p><p><br></p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="typ">Running</span><span class="pln">&nbsp;</span><span class="kwd">from</span><span class="pln">&nbsp;</span><span class="typ">Container</span><span class="pln">&nbsp;</span><span class="kwd">class</span><span class="pun">.</span></li></ol></pre></div></div><p><br></p></div></div>

In [48]:
class Container:

    @classmethod
    def show_details(cls):
        print(f'Running from {cls.__name__} class.')

In [51]:
container = Container()

container.show_details()

<div class="instructions--content--1JI0g"><div class="udlite-heading-xl instructions--title--3vSDk" data-purpose="exercise-title">Exercise 4</div><div data-purpose="safely-set-inner-html:rich-text-viewer:html" class="udlite-text-sm rt-scaffolding"><p>Implement a class named <em>Person </em>which has a class attribute named <em>instances </em>as an empty list. Then, each time you create an instance of the <em>Person </em>class, add it to the <em>Person.instances</em> list (use the <code>__init __()</code> method for this).</p><p>Also implement a class method called <code>count_instances()</code> that returns the number of <em>Person </em>objects created (the number of items in the <em>Person.instances</em> list).</p><p>Create three instances of the Person class. Then call the <code>count_instances()</code> class method and print result to the console.</p><p><br></p><p><strong>Expected result:</strong></p><p><br></p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="lit">3</span></li></ol></pre></div></div><p><br></p></div></div>

In [71]:
class Person:
    
    instances = []
    
    def __init__(self):
        self.instances.append(self)
    
    @classmethod
    def count_instances(cls):
        return print(len(cls.instances))

person1 = Person()
person2 = Person()
person3 = Person()

Person.count_instances()

<div class="instructions--content--1JI0g"><div class="udlite-heading-xl instructions--title--3vSDk" data-purpose="exercise-title">Exercise 5</div><div data-purpose="safely-set-inner-html:rich-text-viewer:html" class="udlite-text-sm rt-scaffolding"><p>A class named <em>Person </em>is given. Modify the <code>__init__()</code> method so that you can set two instance attributes: <em>first_name </em>and <em>last_name </em>(bare attributes, without any validation). </p><p>Create two instances of the <em>Person </em>class<em>.</em> Then call the <code>count_instances()</code> class method and print result to the console.</p><p><br></p><p><strong>Expected result:</strong></p><p><br></p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="lit">2</span></li></ol></pre></div></div><p><br></p></div></div>

In [78]:
class Person:

    instances = []

    def __init__(self, first_name, last_name):
        self.first_name = first_name
        self.last_name = last_name
        Person.instances.append(self)
    
    @classmethod
    def count_instances(cls):
        return len(Person.instances)
    
person1 = Person('John', 'Doe')
person2 = Person('Mike', 'Smith')
print(person1.count_instances())

2


# @staticmethod

<div class="instructions--content--1JI0g"><div class="udlite-heading-xl instructions--title--3vSDk" data-purpose="exercise-title">Exercise 1</div><div data-purpose="safely-set-inner-html:rich-text-viewer:html" class="udlite-text-sm rt-scaffolding"><p>Define a <em>Container </em>class that has a static method (use the <em>staticmethod </em>class - do it in the standard way) named <code>get_current_time()</code> returning the current time in the format <code>'%H:%M:%S'</code>, e.g. <code>'09:45:10'</code>.</p><p><br></p><p><strong>Tip: </strong>Use the built-in <em>time </em>module.</p><p><br></p></div></div>

In [4]:
import time

class Container:
    
    def get_current_time():
        current_time = time.strftime("%H:%M:%S", time.localtime())
        return current_time
    
    get_current_time = get_current_time()
        
print(Container.get_current_time)

15:20:54


<div class="instructions--content--1JI0g"><div class="udlite-heading-xl instructions--title--3vSDk" data-purpose="exercise-title">Exercise 2</div><div data-purpose="safely-set-inner-html:rich-text-viewer:html" class="udlite-text-sm rt-scaffolding"><p>Define a <em>Container </em>class that has a static method (use the <code>@staticmethod</code> decorator) named <code>get_current_time()</code> returning the current time in the format <code>'%H:%M:%S'</code>, e.g. <code>'09:45:10'</code>.</p><p><br></p><p><strong>Tip: </strong>Use the built-in <em>time </em>module.</p><p><br></p></div></div>

In [5]:
import time

class Container:
    
    @staticmethod
    def get_current_time():
        current_time = time.strftime("%H:%M:%S", time.localtime())
        return current_time
        
print(Container.get_current_time())

15:21:07


<div class="instructions--content--1JI0g"><div class="udlite-heading-xl instructions--title--3vSDk" data-purpose="exercise-title">Exercise 3</div><div data-purpose="safely-set-inner-html:rich-text-viewer:html" class="udlite-text-sm rt-scaffolding"><p>Complete the implementation of the <em>Book </em>class. In the <code>__init__()</code> method, set the bare attributes of the instance with names:</p><ul><li><p><em>title</em></p></li><li><p><em>author</em></p></li><li><p><em>book_id</em></p></li></ul><p>Set the instance <em>book_id </em>attribute using the <em>uuid </em>module. Exactly the <code>uuid.uuid4()</code> function from this module. An example of using this function:</p><p><br></p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="kwd">import</span><span class="pln"> uuid</span></li><li class="L1"><span class="pln">&nbsp;</span></li><li class="L2"><span class="pln">&nbsp;</span></li><li class="L3"><span class="pln">str</span><span class="pun">(</span><span class="pln">uuid</span><span class="pun">.</span><span class="pln">uuid4</span><span class="pun">().</span><span class="pln">fields</span><span class="pun">[-</span><span class="lit">1</span><span class="pun">])[:</span><span class="lit">6</span><span class="pun">]</span></li></ol></pre></div></div><p>Returns a 6-element string. This will be the value of the <em>book_id </em>attribute.</p><p>Using the above code, create a static method of the <em>Book </em>class (use the <code>@staticmethod</code> decorator) called <code>get_id()</code>, which will generate a 6-digit <code>str</code> object (the value of the <em>book_id </em>field).</p><p>Then create an instance of the class named <em>book1 </em>with the following arguments:</p><ul><li><p><code>title='Inferno'</code></p></li><li><p><code>author='Dan Brown'</code></p></li></ul><p>In response, print all the <code>__dict__</code> attribute keys of <em>book1 </em>to the console.</p><p><br></p><p><strong>Expected result:</strong></p><p><br></p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="pln">dict_keys</span><span class="pun">([</span><span class="str">'book_id'</span><span class="pun">,</span><span class="pln"> </span><span class="str">'title'</span><span class="pun">,</span><span class="pln"> </span><span class="str">'author'</span><span class="pun">])</span></li></ol></pre></div></div><p><br></p></div></div>

In [6]:
import uuid

In [8]:
str(uuid.uuid4().fields[-1])[:6]

'116052'

In [25]:
import uuid


class Book:

    def __init__(self, title, author):
        self.book_id = self.get_id()
        self.title = title
        self.author = author
    
    @staticmethod
    def get_id():
        return str(uuid.uuid4().fields[-1])[:6]

book = Book('Inferno', 'Dan Brown')

print(book.__dict__.keys())

dict_keys(['book_id', 'title', 'author'])


<div class="instructions--content--1JI0g"><div class="udlite-heading-xl instructions--title--3vSDk" data-purpose="exercise-title">Exercise 4</div><div data-purpose="safely-set-inner-html:rich-text-viewer:html" class="udlite-text-sm rt-scaffolding"><p>The <em>Book </em>class is implemented. Add a <code>__repr__()</code> method to the <em>Book </em>class that represents an instance of this class (see below).</p><p>Then create an instance of the class named <em>book1 </em>passing the following arguments:</p><ul><li><p><code>title='Inferno'</code></p></li><li><p><code>author='Dan Brown'</code></p></li></ul><p>In response, print the instance <em>book1 </em>to the console.</p><p><br></p><p><strong>Expected result:</strong></p><p><br></p><div class="ud-component--base-components--code-block"><div><pre class="prettyprint linenums prettyprinted" role="presentation" style=""><ol class="linenums"><li class="L0"><span class="typ">Book</span><span class="pun">(</span><span class="pln">title</span><span class="pun">=</span><span class="str">'Inferno'</span><span class="pun">,</span><span class="pln"> author</span><span class="pun">=</span><span class="str">'Dan Brown'</span><span class="pun">)</span></li></ol></pre></div></div><p><br></p></div></div>

In [30]:
import uuid


class Book:

    def __init__(self, title, author):
        self.book_id = self.get_id()
        self.title = title
        self.author = author
    
    @staticmethod
    def get_id():
        return str(uuid.uuid4().fields[-1])[:6]
    
    def __repr__(self):
        rep = "Book(title='" + self.title + "', author='" + str(self.author) + "')"
        return rep

book1 = Book('Inferno', 'Dan Brown')

print(repr(book1))

Book(title='Inferno', author='Dan Brown')
